### ISSUE TITLE
`elasticluster list` fails with traceback

### ISSUE THREAD

**Issue by riccardomurri** [gc3-uzh-ch/elasticluster#126]
Running off the "master" branch at commit 6e5dcaa.

        $ elasticluster list
        Traceback (most recent call last):
          File "/home/rmurri/.virtualenvs/elasticluster/bin/elasticluster", line 9, in <module>
            load_entry_point('elasticluster==1.1-dev', 'console_scripts', 'elasticluster')()
          File "/home/rmurri/gc3/elasticluster/elasticluster/main.py", line 178, in main
            app.run()
          File "/home/rmurri/.virtualenvs/elasticluster/local/lib/python2.7/site-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 245, in run
            return self.post_run(returned)
          File "/home/rmurri/.virtualenvs/elasticluster/local/lib/python2.7/site-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 241, in run
            returned = self.main(*args)
          File "/home/rmurri/gc3/elasticluster/elasticluster/main.py", line 166, in main
            return self.params.func()
          File "/home/rmurri/gc3/elasticluster/elasticluster/subcommands.py", line 70, in __call__
            return self.execute()
          File "/home/rmurri/gc3/elasticluster/elasticluster/subcommands.py", line 410, in execute
            clusters = repository.get_all()
          File "/home/rmurri/gc3/elasticluster/elasticluster/repository.py", line 153, in get_all
            clusters.append(self.get(cluster_file))
          File "/home/rmurri/gc3/elasticluster/elasticluster/repository.py", line 167, in get
            cluster = pickle.load(storage)
          File "/usr/lib/python2.7/pickle.py", line 1378, in load
            return Unpickler(file).load()
          File "/usr/lib/python2.7/pickle.py", line 858, in load
            dispatch[key](self)
          File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
            klass = self.find_class(module, name)
          File "/usr/lib/python2.7/pickle.py", line 1126, in find_class
            klass = getattr(mod, name)
        AttributeError: 'module' object has no attribute 'ClusterRepository'

**Comment by nicolasbaer** [comment]
what features should we further improve here?
