### ISSUE TITLE
pip installation fails ... 

### ISSUE THREAD

**Issue by kern3020** [gc3-uzh-ch/elasticluster#147]
Hello, 

When I install elasticluster via pip, it generates the following error. 

```
$ pip install elasticluster
Collecting elasticluster
  Using cached elasticluster-1.2.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-d4Ffsu/elasticluster/setup.py", line 31, in <module>
        del sdist.finders[:]
    AttributeError: 'module' object has no attribute 'finders'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-d4Ffsu/elasticluster/setup.py", line 31, in <module>

        del sdist.finders[:]

    AttributeError: 'module' object has no attribute 'finders'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d4Ffsu/elasticluster
```

I am running python 2.7.6 on ubuntu 14.04 lts. The latest setup.py in elasticluster has a sdist check to see if it has a finders attribute. The comment says this is for newer version of setuptools. I am using setuptools 12.0.5. Any ideas on you to workaround this? 

-jk

**Comment by kern3020** [comment]
Hello, 

I was able to work around this problem but back rev'ing setuptools. The current rev is 12.4. 9.1 works. 10.2 doesn't. 

-jk

**Comment by nicolasbaer** [comment]
Hi
I'd recommend to install the latest version from our master branch. This will fix your issue and include some other improvements. Check the readme for install instructions. 

Cheers

**Comment by brainstorm** [comment]
@nicolasbaer Is there a way I can help fixing up the PyPi package instead of pulling from `master`? Happy to upload a fixed/recent version for easy `pip install elasticluster`!

**Comment by nicolasbaer** [comment]
Usually @arcimboldo takes care of the release. I'll try to take over the process and get a release on pypi within the next days.

**Comment by brainstorm** [comment]
Thanks @nicolasbaer! Is someone taking care of the open pull requests? I would like to volunteer/help out merging those if it's possible.

Thanks in advance!

**Comment by brainstorm** [comment]
Still not working as of today, neither does release 1.2.0's .tar.gz... :/

@guillermo-carrasco

**Comment by stevenwildmanwong** [comment]
unable to install on Centos 7.  
Traceback (most recent call last):
  File "/usr/bin/elasticluster", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/distribute-0.6.19-py2.7.egg/pkg_resources.py", line 2709, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/distribute-0.6.19-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/distribute-0.6.19-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: google-api-python-client

Tried uninstalling google-api-python-client and re-installing.  No difference.

**Comment by jsharpe** [comment]
Installation via pip on ubuntu is still broken, this should not have been closed.

**Comment by sundern** [comment]
Yep, it is broken..
 pip install elasticluster
Collecting elasticluster
  Using cached elasticluster-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dodiumbj/elasticluster/setup.py", line 31, in <module>
        del sdist.finders[:]
    AttributeError: module 'setuptools.command.sdist' has no attribute 'finders'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dodiumbj/elasticluster/

**Comment by riccardomurri** [comment]
Please **do not install ElastiCluster from PyPI**; follow the instructions for installing from GitHub instead: http://elasticluster.readthedocs.io/en/latest/install.html#installing-development-code-from-github

The PyPI code is broken and severely outdated -- even if you get it running, it would not run with Ansible 2.x and possibly many other dependencies.

Again, at the moment please use the GitHub "master" version: http://elasticluster.readthedocs.io/en/latest/install.html#installing-development-code-from-github

This will only be fixed when ElastiCluster 1.3.0 is released.

**Comment by newtorob** [comment]
Github master version installation is broken as well.

**Comment by riccardomurri** [comment]
> Github master version installation is broken as well.

Can you please post the error that you're getting?  What platform (OS, distribution version) are you using?

**Comment by newtorob** [comment]
Sure, I am following this guide [here](https://cloud.google.com/solutions/running-r-at-scale).

Which follows the same installation instructions as those in the guide. So I apologize if I misread (if so can you link me to another installation instruction doc please?). 

I am running this in a virtualenv. Ubuntu 18.04 lts. And here is the error I get: 

```elasticluster --version

Traceback (most recent call last):
  File "/home/rob/.local/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'contextlib2==0.5.5' distribution was not found and is required by schema
```

**Comment by newtorob** [comment]
Actually @riccardomurri I was able to get it running on a server within gcp. So it is probably something on my local machine, I followed the instructions again and it worked. 

Thanks!

**Comment by riccardomurri** [comment]
Great! All is well that ends well :-)

**Comment by newtorob** [comment]
I do continue to get that error locally though, im not sure what this means 

```pkg_resources.DistributionNotFound: The 'contextlib2==0.5.5' distribution was not found and is required by schema
```

**Comment by riccardomurri** [comment]
@newtorob I have tried to install ElastiCluster on a freshly-made Ubuntu 18.04 VM using the instructions at: https://elasticluster.readthedocs.io/en/latest/install.html and ran into no issues.

Python package `contextlib2` is a dependency of package `schema`, which ElastiCluster uses for detecting errors in configuration files; the error you get means that `contextlib2` is not installed on your system, perhaps because an earlier installation attempt was interrupted?

You can try fixing it by running this command within the virtualenv:

    pip install 'contextlib2==0.5.5'

A similar command would fix the other missing dependencies.

However, if you run into many dependency errors, it's just simpler to delete the virtualenv and start again with a new one.  (That's the cool thing about virtualenvs!)

**Comment by newtorob** [comment]
Awesome, that fixed it!
