### ISSUE TITLE
Pbr dependency

### ISSUE THREAD

**Issue by bfilippi** [gc3-uzh-ch/elasticluster#162]
when installing elasticluster it serarches for pbr>=0.11,<2.0
Pypi best match is pbr 1.0.1

But then I get an error 
Installed distribution pbr 1.0.1 conflicts with requirements pbr>=0.6,!=0.7,<1.0

**Comment by bfilippi** [comment]
tried on a different OS 
 same issue 
Benjamins-MacBook-Pro:~ benjaminfilippi$ elasticluster list-templates
Traceback (most recent call last):
  File "/usr/local/bin/elasticluster", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2876, in <module>
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 451, in _build_master
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 464, in _build_from_requirements
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 644, in resolve
pkg_resources.VersionConflict: (pbr 1.0.1 (/usr/local/lib/python2.7/site-packages), Requirement.parse('pbr>=0.6,!=0.7,<1.0'))

**Comment by nicolasbaer** [comment]
This is a bug in the novaclient library documented here: https://bugs.launchpad.net/python-novaclient/+bug/1457100
