### ISSUE TITLE
Network failure when starting SLURM cluster

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#186]
```
Starting cluster `uvslurm-6` with 10 compute nodes.
Starting cluster `uvslurm-6` with 1 frontend nodes.
(this may take a while...)
INFO:gc3.elasticluster:Starting node compute001.
INFO:gc3.elasticluster:Starting node compute002.
INFO:gc3.elasticluster:Starting node compute003.
INFO:gc3.elasticluster:Starting node compute005.
INFO:gc3.elasticluster:Starting node compute004.
INFO:gc3.elasticluster:Starting node compute006.
INFO:gc3.elasticluster:Starting node compute007.
INFO:gc3.elasticluster:Starting node compute008.
INFO:gc3.elasticluster:Starting node compute009.
INFO:gc3.elasticluster:Starting node compute010.
INFO:gc3.elasticluster:_start_node: node 'compute002' has been started
INFO:gc3.elasticluster:Starting node frontend001.
INFO:gc3.elasticluster:_start_node: node 'compute010' has been started
INFO:gc3.elasticluster:_start_node: node 'compute003' has been started
INFO:gc3.elasticluster:_start_node: node 'compute006' has been started
INFO:gc3.elasticluster:_start_node: node 'compute005' has been started
INFO:gc3.elasticluster:_start_node: node 'compute004' has been started
INFO:gc3.elasticluster:_start_node: node 'compute009' has been started
INFO:gc3.elasticluster:_start_node: node 'compute001' has been started
INFO:gc3.elasticluster:_start_node: node 'frontend001' has been started
INFO:gc3.elasticluster:_start_node: node 'compute007' has been started
INFO:gc3.elasticluster:_start_node: node 'compute008' has been started
Traceback (most recent call last):
  File "/home/centos/src/venv/elasticluster/bin/elasticluster", line 9, in <module>
    load_entry_point('elasticluster==1.3-dev', 'console_scripts', 'elasticluster')()
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 187, in main
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 245, in run
    return self.post_run(returned)
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 241, in run
    returned = self.main(*args)
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 175, in main
  File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 82, in __call__
  File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 201, in execute
  File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 536, in start
  File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 946, in connect
  File "build/bdist.linux-x86_64/egg/paramiko/client.py", line 265, in connect
  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 408, in start_client
EOFError
```

**Comment by verdurin** [comment]
More detail on one of the node connection attempts:

```
fatal: [compute010] => Traceback (most recent call last):
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/ansible-1.9.3-py2.7.egg/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/ansible-1.9.3-py2.7.egg/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/ansible-1.9.3-py2.7.egg/ansible/runner/__init__.py", line 968, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file, delegate_host)
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/ansible-1.9.3-py2.7.egg/ansible/runner/connection.py", line 35, in connect
    conn = utils.plugins.connection_loader.get(transport, self.runner, host, port, user=user, password=password, private_key_file=private_key_file)
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/ansible-1.9.3-py2.7.egg/ansible/utils/plugins.py", line 219, in get
    return getattr(self._module_cache[path], self.class_name)(*args, **kwargs)
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/ansible-1.9.3-py2.7.egg/ansible/runner/connection_plugins/ssh.py", line 44, in __init__
    self.ipv6 = ':' in self.host
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by verdurin** [comment]
Closing this issue, because I think the problems are with our cloud, not with Elasticluster per se.
