### ISSUE TITLE
Installation error: TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by mbookman** [gc3-uzh-ch/elasticluster#189]
At the end of installing Elasticluster from source, "python setup.py install" errors out with:

    Finished processing dependencies for elasticluster==1.3.dev0
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
        func(*targs, **kargs)
      File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
        info('process shutting down')
    TypeError: 'NoneType' object is not callable
    Error in atexit._run_exitfuncs:
    <several iterations of this>

This appears to be an issue fixed long ago, but for Python 2.7 (which I am using), it requires a patch:

https://bugs.python.org/issue15881

https://hg.python.org/cpython/rev/0a58fa8e9bac

The error itself seems innocuous, since it is just Python crashing as it exits.

However, I have tested the suggested workaround, which is to add the following to setup.py:

    try:
        import multiprocessing
    except ImportError:
        pass

and it leads to a clean exit.

**Comment by riccardomurri** [comment]
I have just pushed commit aa2d612 with your fix into the `master` branch.  Can you please confirm that it fixes the issue?

**Comment by mbookman** [comment]
Thanks Riccardo. Tested it two different systems and exit is now clean.
