### ISSUE TITLE
Traceback while trying to stop a node that never started ...

### ISSUE THREAD

**Issue by riccardomurri** [gc3-uzh-ch/elasticluster#206]
If some error occurs starting a node, ElastiCluster will store
Python's `None` for the instance value; however, it tries to stop this
non-instance nonetheless during the final cleanup phase, and -of
course- fails with a misleading traceback::

        $ elasticluster start foo
        ...
        ERROR:gc3.elasticluster:Stopping node `compute001`, since we could not connect to it within the timeout.
        INFO:gc3.elasticluster:shutting down instance `None`
        Traceback (most recent call last):
          File "/home/ubuntu/elasticluster/bin/elasticluster", line 9, in <module>
            load_entry_point('elasticluster==1.3-dev', 'console_scripts', 'elasticluster')()
          File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 187, in main
          File "/home/ubuntu/elasticluster/local/lib/python2.7/site-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 245, in run
            return self.post_run(returned)
          File "/home/ubuntu/elasticluster/local/lib/python2.7/site-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 241, in run
            returned = self.main(*args)
          File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 175, in main
          File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 82, in __call__
          File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 201, in execute
          File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 556, in start
          File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 373, in remove_node
          File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 871, in stop
          File "build/bdist.linux-x86_64/egg/elasticluster/providers/openstack.py", line 149, in stop_instance
          File "build/bdist.linux-x86_64/egg/elasticluster/providers/openstack.py", line 304, in _load_instance
          File "/home/ubuntu/elasticluster/local/lib/python2.7/site-packages/python_novaclient-2.31.0-py2.7.egg/novaclient/v2/servers.py", line 549, in get
            return self._get("/servers/%s" % base.getid(server), "server")
          File "/home/ubuntu/elasticluster/local/lib/python2.7/site-packages/python_novaclient-2.31.0-py2.7.egg/novaclient/base.py", line 167, in _get
            _resp, body = self.api.client.get(url)
          File "/home/ubuntu/elasticluster/local/lib/python2.7/site-packages/python_novaclient-2.31.0-py2.7.egg/novaclient/client.py", line 446, in get
            return self._cs_request(url, 'GET', **kwargs)
          File "/home/ubuntu/elasticluster/local/lib/python2.7/site-packages/python_novaclient-2.31.0-py2.7.egg/novaclient/client.py", line 438, in _cs_request
            raise e
        novaclient.exceptions.Unauthorized: Unauthorized (HTTP 401) (Request-ID: req-6147b5d7-27a1-4c90-bc55-36c42e83b5ef)

**Comment by riccardomurri** [comment]
This is related (likely: the same) as issue #155
