### ISSUE TITLE
Bug with ansible >= 2.0.0.0

### ISSUE THREAD

**Issue by PeterVermont** [gc3-uzh-ch/elasticluster#236]
Looks like elasticluster requires ansible 1.9.4 because later versions cause this error:

> elasticluster list
Traceback (most recent call last):
  File "/home/andrewsp/anaconda/bin/elasticluster", line 9, in <module>
    load_entry_point('elasticluster==1.3.dev0', 'console_scripts', 'elasticluster')()
  File "/home/andrewsp/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 549, in load_entry_point
  File "/home/andrewsp/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 2542, in load_entry_point
  File "/home/andrewsp/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 2202, in load
  File "/home/andrewsp/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 2208, in resolve
  File "build/bdist.linux-x86_64/egg/elasticluster/__init__.py", line 31, in <module>
  File "build/bdist.linux-x86_64/egg/elasticluster/providers/ansible_provider.py", line 30, in <module>
ImportError: No module named callbacks

**Comment by riccardomurri** [comment]
This should be fixed in the "develop" branch -- can you please try it out?

**Comment by PeterVermont** [comment]
Sorry for delay. When I switched to develop and re-ran setup.py install it donwgraded ansible and no longer gave the above error. When I manually upgraded ansible and ran elasticluster list it correctly showed error that ansible version did not match requirements.

Note that my outstanding bug #235 is still true -- the gridengine system does not appear to be installed on the cluster.

**Comment by tomsing1** [comment]
I ran into the same problem when I tried to install elasticluster using the branch maintained by Google Genomics and filed [this issue](https://github.com/googlegenomics/readthedocs/issues/127).

Could this issue be fixed in the master branch now as well?

**Comment by tomsing1** [comment]
Never mind, this issue is fixed now.
