### ISSUE TITLE
Failure to setup config file in new installation from Github

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#251]
I've just installed from Github.

Running `elasticluster list` to generate a commented config file fails with the following error:

```
elasticluster list
Traceback (most recent call last):
  File "/home/centos/src/github/elasticluster/bin/elasticluster", line 9, in <module>
    load_entry_point('elasticluster==1.3.dev0', 'console_scripts', 'elasticluster')()
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 196, in main
  File "/home/centos/src/github/elasticluster/lib/python2.7/site-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 235, in run
    self.pre_run()
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 151, in pre_run
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1159, in resource_filename
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1704, in get_resource_filename
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1725, in _extract_resource
KeyError: 'elasticluster/share/elasticluster/etc/config.template'
```

**Comment by riccardomurri** [comment]
This should be fixed in the latest commit to branch "develop": https://github.com/gc3-uzh-ch/elasticluster/commit/cb7ea07eceb1d6fe8f9749aba73b882246d3735a

Can you please check?

**Comment by verdurin** [comment]
Yes, that fixes the creation of a new default config file - thanks.
