### ISSUE TITLE
Optional configuration key <class>_min_nodes invalid name error

### ISSUE THREAD

**Issue by corburn** [gc3-uzh-ch/elasticluster#279]
`elasticluster list-templates` raises an Invalid name error when the configuration cluster section includes the optional \<class\>_min_nodes  keys.
```
[cluster/slurm]
cloud=google
login=google
setup_provider=ansible-slurm
security_group=default
image_id=ubuntu-1604-xenial-v20160610
flavor=n1-standard-1
frontend_nodes=1
compute_nodes=3
image_userdata=
ssh_to=frontend
frontend_min_nodes=1
compute_min_nodes=1
```

> Error: Invalid name `frontend_min` for node group. A valid node group can only consist of letters, digits or the hyphen character (`-`)
Exiting.

**Comment by riccardomurri** [comment]
This should now be fixed in commit dd63b1f -- can you please check?

**Comment by corburn** [comment]
Hi @riccardomurri, I will check this evening.

**Comment by corburn** [comment]
Hello @riccardomurri,

With the `*_nodes_min` properties present, elasticluster crashed with the attached stack trace. Without the properties, elasticluster succeeded up until the Ansible issues I am trying to fix in #292 

Elasticluster version: c3ff0aaf5017dd6388229a9bf11d0b39cb7f8fe2

```
[cluster/slurm]
cloud=google
login=google
setup_provider=ansible-slurm
security_group=default
image_id=ubuntu-1604-xenial-v20160610
flavor=f1-micro
frontend_nodes=1
compute_nodes=3
frontend_nodes_min=1
compute_nodes_min=1
```

```
root@elasticluster:~# elasticluster start -n foobar slurm
Starting cluster `foobar` with 1 frontend nodes.
Starting cluster `foobar` with 3 compute nodes.
(this may take a while...)
Traceback (most recent call last):
  File "/usr/local/bin/elasticluster", line 9, in <module>
    load_entry_point('elasticluster==1.3.dev0', 'console_scripts', 'elasticluster')()
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 205, in main
  File "/usr/local/lib/python2.7/dist-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 245, in run
    return self.post_run(returned)
  File "/usr/local/lib/python2.7/dist-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 241, in run
    returned = self.main(*args)
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 191, in main
  File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 86, in __call__
  File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 202, in execute
  File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 617, in start
AttributeError: 'list' object has no attribute 'iteritems'
```

**Comment by riccardomurri** [comment]
Thanks for testing and reporting back!

Should be fixed in commit 4b5cdf1 (laster "master"), can you please try again?

**Comment by corburn** [comment]
Success. The attached stack trace is the result of requesting 1 compute node with a minimum of 3. Would it be worth checking for such an invalid configuration before attempting to provision the machines?

```
`Your cluster could not start `The cluster does not provide the minimum amount of nodes specified in the configuration. The nodes are still running, but will not be setup yet. Please change the minimum amount of nodes in the configuration or try to start a new cluster after checking the cloud provider settings.`
Traceback (most recent call last):
  File "/usr/local/bin/elasticluster", line 9, in <module>
    load_entry_point('elasticluster==1.3.dev0', 'console_scripts', 'elasticluster')()
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 205, in main
  File "/usr/local/lib/python2.7/dist-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 245, in run
    return self.post_run(returned)
  File "/usr/local/lib/python2.7/dist-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 241, in run
    returned = self.main(*args)
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 191, in main
  File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 86, in __call__
  File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 202, in execute
  File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 621, in start
  File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 646, in _check_cluster_size
elasticluster.exceptions.ClusterError: The cluster does not provide the minimum amount of nodes specified in the configuration. The nodes are still running, but will not be setup yet. Please change the minimum amount of nodes in the configuration or try to start a new cluster after checking the cloud provider settings.
```

**Comment by riccardomurri** [comment]
> Would it be worth checking for such an invalid configuration before attempting to provision the machines?

Indeed. I tried to add that check, but `conf.py` is really hard to understand and modify - so adding that simple check makes 3 different tests fail...  I guess I'll have to rewrite substantial portions of the configuration file reader so it'll have to wait at least a couple of weeks.
