### ISSUE TITLE
Setuptools-related installation failure on CentOS 7.2

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#288]
Just tried installing from GitHub on a CentOS 7.2 VM.

When I try to run the installation:

```
(elasticluster)[centos@pilot6-admin src]$ python setup.py install
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-20.6.8.zip
Extracting in /tmp/tmpCjuDis
Now working in /tmp/tmpCjuDis/setuptools-20.6.8
Building a Setuptools egg in /home/centos/src/elasticluster/src
warning: no files found matching '*.py' under directory '_markerlib'
warning: no files found matching '*' under directory 'setuptools/_vendor'
warning: no files found matching '*.txt'
/home/centos/src/elasticluster/src/setuptools-20.6.8-py2.7.egg
/home/centos/src/elasticluster/src/setuptools-20.6.8-py2.7.egg/setuptools/dist.py:285: UserWarning: Normalizing '1.3.dev' to '1.3.dev0'
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/test-easy-install-13801.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/lib/python2.7/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.
```

**Comment by verdurin** [comment]
Looks like it's trying to install to system paths, instead of the local virtualenv?

**Comment by verdurin** [comment]
Hmm - re-running this, after having upgraded the local `python-setuptools`, and it works. However, it fails at the point where it needs `GCC`. Yes, `GCC` should be installed, but this should be mentioned in the installation documentation:

```
Running netifaces-0.10.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-J1dXan/netifaces-0.10.4/egg-dist-tmp-_sOxas
checking for getifaddrs...not found.
checking for getnameinfo...not found.
checking for socket IOCTLs...not found.
checking for optional header files...none found.
checking whether struct sockaddr has a length field...no.
checking which sockaddr_xxx structs are defined...none!
checking for routing socket support...no.
checking for sysctl(CTL_NET...) support...no.
checking for netlink support...no.
unable to execute gcc: No such file or directory
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

**Comment by verdurin** [comment]
With `GCC` installed, the next error:

```
Searching for oslo.serialization>=1.10.0
Reading https://pypi.python.org/simple/oslo.serialization/
Best match: oslo.serialization 2.9.0
Downloading https://pypi.python.org/packages/bf/4f/2c7a93ed7061ba7c58cf00d42fd25fe163bd9ea84265f62920e29317769f/oslo.serialization-2.9.0.tar.gz#md5=bdb495d8118fe45183ba30295d8d3e79
Processing oslo.serialization-2.9.0.tar.gz
Writing /tmp/easy_install-IuCFzY/oslo.serialization-2.9.0/setup.cfg
Running oslo.serialization-2.9.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-IuCFzY/oslo.serialization-2.9.0/egg-dist-tmp-nweU1g
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/centos/src/elasticluster/elasticluster-2016-06-24/lib/python2.7/site-packages/pbr-1.10.0-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/centos/src/elasticluster/elasticluster-2016-06-24/lib/python2.7/site-packages/pbr-1.10.0-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/home/centos/src/elasticluster/elasticluster-2016-06-24/lib/python2.7/site-packages/pbr-1.10.0-py2.7.egg/pbr/util.py", line 382, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 132, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-IuCFzY/oslo.serialization-2.9.0/setup.cfg: TypeError: dist must be a Distribution instance
```

**Comment by verdurin** [comment]
Okay, I think this is ultimately another case of #268 - @riccardomurri could you merge the branch with that fix?

**Comment by riccardomurri** [comment]
@verdurin Is this still an issue?
