### ISSUE TITLE
Unable to start properly a cluster

### ISSUE THREAD

**Issue by radaniba** [gc3-uzh-ch/elasticluster#302]
Hello all,

I used elasticluster with no issues at all with instances with small flavours (up to medium) and today I tried to create a cluster with bigger instances (XL)

So I was trying to get the new cluster set up but couldnt do it for a recurring problem that I am having a hard time to understand

```
Starting cluster `gridengine` with 1 frontend nodes.
Starting cluster `gridengine` with 7 xlcompute nodes.
(this may take a while...)
2016-08-10 21:01:19 devrad gc3.elasticluster[15608] ERROR could not start node `xlcompute002` for reason `__init__() got an unexpected keyword argument 'retry_after'`
         2016-08-10 21:11:19 devrad gc3.elasticluster[15608] ERROR Not all nodes were started correctly within the given timeout `600`
2016-08-10 21:11:19 devrad gc3.elasticluster[15608] ERROR Please check if image, keypair, and network configuration is correct and try again.
          2016-08-10 21:21:19 devrad gc3.elasticluster[15608] ERROR Could not connect to all the nodes of the cluster within the given timeout `600`.
2016-08-10 21:21:19 devrad gc3.elasticluster[15608] ERROR Stopping node `xlcompute002`, since we could not connect to it within the timeout.
Traceback (most recent call last):
  File "/usr/local/bin/elasticluster", line 9, in <module>
    load_entry_point('elasticluster==1.2.1rc1', 'console_scripts', 'elasticluster')()
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 189, in main
  File "/usr/local/lib/python2.7/dist-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 245, in run
    return self.post_run(returned)
  File "/usr/local/lib/python2.7/dist-packages/pyCLI-2.0.3-py2.7.egg/cli/app.py", line 241, in run
    returned = self.main(*args)
  File "build/bdist.linux-x86_64/egg/elasticluster/main.py", line 177, in main
  File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 82, in __call__
  File "build/bdist.linux-x86_64/egg/elasticluster/subcommands.py", line 201, in execute
  File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 557, in start
  File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 374, in remove_node
  File "build/bdist.linux-x86_64/egg/elasticluster/cluster.py", line 880, in stop
  File "build/bdist.linux-x86_64/egg/elasticluster/providers/openstack.py", line 155, in stop_instance
  File "build/bdist.linux-x86_64/egg/elasticluster/providers/openstack.py", line 322, in _load_instance
elasticluster.exceptions.InstanceError: the given instance `None` was not found on the coud

```

my config is like : 

```
[cluster/ge]
cloud=collab
login=ubuntu
setup_provider=ansible-gridengine
security_group=raniba-sg
security_group=default
image_id=b2527be2-562f-4477-b722-b0ae90025edf
flavor=c1.medium
frontend_nodes=1
xlcompute_nodes=6
ssh_to=frontend

[cluster/ge/lcompute]
flavor=c1.large

[cluster/ge/xlcompute]
flavor=c1.xlarge

```

any idea on how this happened ?

**Comment by riccardomurri** [comment]
Hello @radaniba 

`retry_after` is a parameter to the OpenStack API, so if it's not accepted there is possibly a version mismatch. What version of the `novaclient` and `keystoneauth1` packages are you using together with ElastiCluster?  And what version of Python?

**Comment by riccardomurri** [comment]
@radaniba is this issue still current?
