### ISSUE TITLE
`elasticluster start` crashes when invoked again after cluster start failure.

### ISSUE THREAD

**Issue by riccardomurri** [gc3-uzh-ch/elasticluster#313]
Context: cluster start operation fails because of wrong image ID in
configuration file::

    $ elasticluster start ubuntu
    Starting cluster `ubuntu` with 8 worker nodes.
    Starting cluster `ubuntu` with 1 master nodes.
    (this may take a while...)
    [...]
    2016-10-06 09:23:54 xenia gc3.elasticluster[25623] ERROR Could not start node `worker002`: No image found with id 'b66c1331-adfd-4c33-813c-d841a6c36506' on cloud https://cloud.s3it.uzh.ch:5000/v2.0
    [...]
    2016-10-06 09:23:54 xenia gc3.elasticluster[25623] ERROR Could not start node `worker007`: No image found with id 'b66c1331-adfd-4c33-813c-d841a6c36506' on cloud https://cloud.s3it.uzh.ch:5000/v2.0
    2016-10-06 09:24:24 xenia gc3.elasticluster[25623] ERROR Not all nodes were started correctly within the given timeout `30`
    2016-10-06 09:24:24 xenia gc3.elasticluster[25623] ERROR Please check if image, keypair, and network configuration is correct and try again.
    2016-10-06 09:24:54 xenia gc3.elasticluster[25623] ERROR Could not connect to all the nodes of the cluster within the given timeout `30`.
    2016-10-06 09:24:54 xenia gc3.elasticluster[25623] ERROR Stopping node `worker001`, since we could not connect to it within the timeout.
    [...]
    2016-10-06 09:24:54 xenia gc3.elasticluster[25623] ERROR Stopping node `worker008`, since we could not connect to it within the timeout.
    2016-10-06 09:24:55 xenia gc3.elasticluster[25623] ERROR Stopping node `master001`, since we could not connect to it within the timeout.
    [...]

The cluster state is saved as such in the storage location::

    $ cat ~/.elasticluster/storage/ubuntu.yaml
    extra:
        flavor: 4cpu-16ram-hpc
        image_id: b66c1331-adfd-4c33-813c-d841a6c36506
        login: ubuntu
        master_nodes: '1'
        network_ids: c86b320c-9542-4032-a951-c8a068894cc2
        security_group: default
        worker_nodes: '8'
    keep_running: true
    name: ubuntu
    nodes:
        master: []
        worker: []
    ssh_to: master
    template: ubuntu
    thread_pool_max_size: 10
    user_key_name: rmurri
    user_key_private: /home/rmurri/...
    user_key_public: /home/rmurri/....

Now, trying to start the same cluster again leads to this error traceback::

    $ elasticluster start ubuntu
    [...]
    (this may take a while...)
    Traceback (most recent call last):
      File "/home/rmurri/.virtualenvs/elasticluster-dev/bin/elasticluster", line 11, in <module>
        load_entry_point('elasticluster', 'console_scripts', 'elasticluster')()
      File "/home/rmurri/w/elasticluster/elasticluster/main.py", line 205, in main
        app.run()
      [...]
      File "/home/rmurri/w/elasticluster/elasticluster/subcommands.py", line 196, in execute
        cluster.start(min_nodes=min_nodes)
      File "/home/rmurri/w/elasticluster/elasticluster/cluster.py", line 485, in start
        self.thread_pool_max_size))
      File "/usr/lib/python2.7/multiprocessing/dummy/__init__.py", line 151, in Pool
        return ThreadPool(processes, initializer, initargs)
      File "/usr/lib/python2.7/multiprocessing/pool.py", line 727, in __init__
        Pool.__init__(self, processes, initializer, initargs)
      File "/usr/lib/python2.7/multiprocessing/pool.py", line 152, in __init__
        raise ValueError("Number of processes must be at least 1")
    ValueError: Number of processes must be at least 1

**Comment by riccardomurri** [comment]
Apparently the bug is triggered only if we allow ElastiCLuster to timeout and start the "Stopping node ..." dance -- if `elasticluster start` is stopped before that, the YAML file has the correct content and trying to start a cluster again yield the correct results.
