### ISSUE TITLE
Missing dependencies for setuptools

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#382]
The new error message suggests I need to upgrade the installed version of `setuptools` on `CentOS 7.2`:

```
Obtaining file:///home/centos/src/venv-2017-01-24/elasticluster/src
  Running setup.py egg_info for package from file:///home/centos/src/venv-2017-01-24/elasticluster/src

    The required version of setuptools (>=21.0.0) is not available,
    and can't be installed while this script is running. Please
    install a more recent version first, using
    'pip install --upgrade setuptools'.

    (Currently using setuptools 0.9.8 (/home/centos/src/venv-2017-01-24/elasticluster/lib/python2.7/site-packages))
```

and when I run that:
```
pip install --upgrade setuptools
Downloading/unpacking setuptools from https://pypi.python.org/packages/b1/d1/3df86b914d72b18d37266f964a11576f135eadbb7d2e3c5165377e4263bc/setuptools-34.0.1.zip#md5=9e907950a94d38c0295df0da2507c280
  Downloading setuptools-34.0.1.zip (617kB): 617kB downloaded
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named six.moves
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named six.moves
```

**Comment by verdurin** [comment]
If I install `six` I then see:
```
pip install --upgrade setuptools
Downloading/unpacking setuptools from https://pypi.python.org/packages/b1/d1/3df86b914d72b18d37266f964a11576f135eadbb7d2e3c5165377e4263bc/setuptools-34.0.1.zip#md5=9e907950a94d38c0295df0da2507c280
  Downloading setuptools-34.0.1.zip (617kB): 617kB downloaded
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named packaging.version
```

**Comment by verdurin** [comment]
Then I had to install `packaging` and `appdirs`, and at last the `setuptools` upgrade completed.

**Comment by verdurin** [comment]
In summary, the following dependencies need to be added for the `virtualenv` install from github:
`six`, `packaging` and `appdirs`.

**Comment by riccardomurri** [comment]
Can you please check if using `easy_install setuptools` works without the need for additional packages?

**Comment by riccardomurri** [comment]
Hmmm... No, `easy_install` won't work -- ends up in a "maximum recursion exceeded" error like in GC3Pie's https://github.com/uzh/gc3pie/issues/604 

I wonder how is one supposed to bootstrap the Python packaging infrastructure today?

**Comment by riccardomurri** [comment]
Anyway, your assessment is correct and this `pip` invocation seems to do the job::

    pip install six packaging appdirs; pip install --upgrade setuptools
