### ISSUE TITLE
Cannot start nodes on OpenStack cloud using the `libcloud` provider

### ISSUE THREAD

**Issue by riccardomurri** [gc3-uzh-ch/elasticluster#437]
Using the example configuration for using OpenStack with the newly-added
`libcloud` provider, I get the following error::

    2017-05-22 16:31:17 xenia gc3.elasticluster[1925] ERROR Could not start node `master001`: 'str' object has no attribute 'id' -- <type 'exceptions.AttributeError'>
    Traceback (most recent call last):
      File "/home/rmurri/w/elasticluster/elasticluster/cluster.py", line 493, in _start_node
        node.start()
      File "/home/rmurri/w/elasticluster/elasticluster/cluster.py", line 1085, in start
        **self.extra)
      File "/home/rmurri/w/elasticluster/elasticluster/providers/libcloud_provider.py", line 89, in start_instance
        node = self.driver.create_node(**options)
      File "/home/rmurri/.virtualenvs/elasticluster-dev/local/lib/python2.7/site-packages/libcloud/compute/drivers/openstack.py", line 1259, in create_node
        server_params = self._create_args_to_params(None, **kwargs)
      File "/home/rmurri/.virtualenvs/elasticluster-dev/local/lib/python2.7/site-packages/libcloud/compute/drivers/openstack.py", line 1371, in _create_args_to_params
        server_params['imageRef'] = kwargs.get('image').id
    AttributeError: 'str' object has no attribute 'id'

It looks like there's some parameter name mismatch (or a wrongly-adapted
parameter).

**Comment by witlox** [comment]
look like our imageid is not being resolved to an image object, will inspect

**Comment by witlox** [comment]
correction, refactoring made a likely check of list functions to an exact check of list functions, wait with checking need to update code...

**Comment by witlox** [comment]
done

**Comment by riccardomurri** [comment]
Nope... same error.

The issue *may* be that the image ID I have in the config file is invalid and so some critical data structure is filled incorrectly; but this should be caught and properly handled.
