### ISSUE TITLE
AttributeError: 'module' object has no attribute 'finders'

### ISSUE THREAD

**Issue by maikenp** [gc3-uzh-ch/elasticluster#448]
Installing elasticluster on centos7 and following instructions in your documentation 
(Prepare the environment for installation, and Install required dependencies ) 

I first get problem documented in the Troubleshooting document: http://elasticluster.readthedocs.io/en/latest/troubleshooting.html#installation-fails-with-versionconflict-requirement-parse-setuptools-17-1
and solve this following the instructions. 

After this I again do
```
(elasticluster)[centos@elasticluster-test ~]$ pip install elasticluster
Downloading/unpacking elasticluster
  Downloading elasticluster-1.2.tar.gz (1.3MB): 1.3MB downloaded
  Running setup.py egg_info for package elasticluster
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/centos/elasticluster/build/elasticluster/setup.py", line 31, in <module>
        del sdist.finders[:]
    AttributeError: 'module' object has no attribute 'finders'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/centos/elasticluster/build/elasticluster/setup.py", line 31, in <module>

    del sdist.finders[:]

AttributeError: 'module' object has no attribute 'finders'

```

pip.log attached
[pip.log.txt](https://github.com/gc3-uzh-ch/elasticluster/files/1060997/pip.log.txt)

**Comment by riccardomurri** [comment]
Hello,

After this I again do
>
> (elasticluster)[centos@elasticluster-test ~]$ pip install elasticluster
>
>
 Installing ElastiCluster from PyPI (= `pip install elasticluster`) is
currently broken.  Can you please install the development version from
GitHub, using the instructions at the following URL?

http://elasticluster.readthedocs.io/en/latest/install.html#installing-development-code-from-github

**Comment by maikenp** [comment]
Thank you. I did that. Now I get: 
``
(elasticluster)[centos@elasticluster-test src]$ elasticluster list-templates
Traceback (most recent call last):
  File "/home/centos/elasticluster/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/centos/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/home/centos/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/centos/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 969, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/centos/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pathlib2' distribution was not found and is required by azure-datalake-store
``

**Comment by maikenp** [comment]
After doing 
``
pip install pathlib2
pip install functools32
pip install scandir
pip install secretstorage
``
since it seems these packages were missing I could run the elasticluster list-templates command
``
(elasticluster)[centos@elasticluster-test src]$ elasticluster list-templates
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] WARNING Deploying default configuration file to /home/centos/.elasticluster/config.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] WARNING UserWarning: Configuration key `setup_provider` in section `cluster/aws-slurm` should be renamed to `setup` -- please update configuration file(s). Support for automatic renaming will be removed in release 2.0 of ElastiCluster.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] WARNING UserWarning: Configuration key `setup_provider` in section `cluster/torque` should be renamed to `setup` -- please update configuration file(s). Support for automatic renaming will be removed in release 2.0 of ElastiCluster.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] WARNING UserWarning: Configuration key `setup_provider` in section `cluster/slurm` should be renamed to `setup` -- please update configuration file(s). Support for automatic renaming will be removed in release 2.0 of ElastiCluster.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] WARNING UserWarning: Configuration key `setup_provider` in section `cluster/hadoop` should be renamed to `setup` -- please update configuration file(s). Support for automatic renaming will be removed in release 2.0 of ElastiCluster.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] WARNING UserWarning: Configuration key `setup_provider` in section `cluster/matlab` should be renamed to `setup` -- please update configuration file(s). Support for automatic renaming will be removed in release 2.0 of ElastiCluster.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] WARNING UserWarning: Configuration key `setup_provider` in section `cluster/ipython` should be renamed to `setup` -- please update configuration file(s). Support for automatic renaming will be removed in release 2.0 of ElastiCluster.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR In section `login/google`: Key 'user_key_public' error:
readable_file('~/.ssh/id_rsa.pub') raised ValueError('cannot read file `~/.ssh/id_rsa.pub`',)
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR Dropping configuration section `login/google` because of the above errors
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR In section `login/ubuntu`: Key 'user_key_public' error:
readable_file('~/.ssh/id_rsa.pub') raised ValueError('cannot read file `~/.ssh/id_rsa.pub`',)
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR Dropping configuration section `login/ubuntu` because of the above errors
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR In section `login/gc3-user`: Key 'user_key_public' error:
readable_file('~/.ssh/id_rsa.pub') raised ValueError('cannot read file `~/.ssh/id_rsa.pub`',)
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR Dropping configuration section `login/gc3-user` because of the above errors
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR In section `cloud/google`: Missing keys: <type 'str'>
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR Dropping configuration section `cloud/google` because of the above errors
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR Configuration section `cluster/aws-slurm` references non-existing login section `ubuntu`. Dropping cluster definition.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR Configuration section `cluster/torque` references non-existing login section `gc3-user`. Dropping cluster definition.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR Configuration section `cluster/slurm` references non-existing login section `gc3-user`. Dropping cluster definition.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR Configuration section `cluster/hadoop` references non-existing login section `gc3-user`. Dropping cluster definition.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR Configuration section `cluster/matlab` references non-existing login section `gc3-user`. Dropping cluster definition.
2017-06-12 14:40:31 elasticluster-test gc3.elasticluster[19218] ERROR Configuration section `cluster/ipython` references non-existing cloud section `google`. Dropping cluster definition.
0 cluster templates found in configuration file.
``
Is this output as expected?

**Comment by riccardomurri** [comment]
Yes, this is expected -- the template configuration file is just an example and in particular cannot contain any valid `[cloud/*]` sections (since these need actual authentication data to work).

**Comment by maikenp** [comment]
Very good, then I am on track here. Thanks.

**Comment by riccardomurri** [comment]
Good, then I'll close the issue ;-)
