### ISSUE TITLE
pbr version conflict when running command elasticluster list-templates

### ISSUE THREAD

**Issue by maikenp** [gc3-uzh-ch/elasticluster#451]
Installed elasticluster following: https://elasticluster.readthedocs.io/en/latest/install.html#installing-development-code-from-github

This is on centos6, with python 2.6.6
I see I have pbr version 3.0.1

``
(elasticluster)[centos@elasticluster src]$ elasticluster list-templates
Traceback (most recent call last):
  File "/home/centos/elasticluster/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pbr!=0.7,<1.0,>=0.6' distribution was not found and is required by python-cinderclient
(elasticluster)[centos@elasticluster src]$ pip install pbr
``

**Comment by maikenp** [comment]
Any tips for solving this?

**Comment by riccardomurri** [comment]
Can you please run the following command and post the output here?

    egrep 'Requires-Dist: pbr ' /home/centos/elasticluster/lib/python2.6/site-packages/*.dist-info/METADATA

**Comment by maikenp** [comment]
Thanks, it gives:

``
(elasticluster)[centos@elasticluster` ~]$ egrep 'Requires-Dist: pbr ' /home/centos/elasticluster/lib/python2.6/site-packages/*.dist-info/METADATA
/home/centos/elasticluster/lib/python2.6/site-packages/debtcollector-0.10.0.dist-info/METADATA:Requires-Dist: pbr (>=1.6)
/home/centos/elasticluster/lib/python2.6/site-packages/oslo.i18n-3.0.0.dist-info/METADATA:Requires-Dist: pbr (>=1.6)
/home/centos/elasticluster/lib/python2.6/site-packages/oslo.serialization-2.0.0.dist-info/METADATA:Requires-Dist: pbr (>=1.6)
/home/centos/elasticluster/lib/python2.6/site-packages/oslo.utils-3.0.0.dist-info/METADATA:Requires-Dist: pbr (>=1.6)
/home/centos/elasticluster/lib/python2.6/site-packages/python_cinderclient-1.2.1.dist-info/METADATA:Requires-Dist: pbr (>=0.6,!=0.7,<1.0)
/home/centos/elasticluster/lib/python2.6/site-packages/python_keystoneclient-1.8.1.dist-info/METADATA:Requires-Dist: pbr (>=1.6)
/home/centos/elasticluster/lib/python2.6/site-packages/python_novaclient-2.35.0.dist-info/METADATA:Requires-Dist: pbr (>=1.6)
/home/centos/elasticluster/lib/python2.6/site-packages/stevedore-1.9.0.dist-info/METADATA:Requires-Dist: pbr (>=1.6)``

**Comment by riccardomurri** [comment]
Can you please try running::

    pip install 'python-cinderclient==1.5.0' 'pbr>=1.6'

**Comment by maikenp** [comment]
Thanks, it gives now 

(elasticluster)[centos@elasticluster ~]$ elasticluster list-templates
Traceback (most recent call last):
  File "/home/centos/elasticluster/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-cinderclient<1.2.2' distribution was not found and is required by elasticluster

**Comment by riccardomurri** [comment]
Can you please edit file `setup.py` and change line 110 to read::

    'python-cinderclient<1.6.0',

instead of `python-cinderclient<1.2.2`.

Then re-run `pip install -e .` in the `elasticluster/` directory.

**Comment by maikenp** [comment]
Great, I think that fixed the issue! Thanks a lot.

**Comment by maikenp** [comment]
Thanks a lot for your help!
_______________________________
Maiken Pedersen
Research Computing Services, USIT
University of Oslo, Norway
mob: +47 466 28 328


On 20 Jun 2017, at 11:28, Riccardo Murri <notifications@github.com<mailto:notifications@github.com>> wrote:


This should now be fixed in commit 8be18f8<https://github.com/gc3-uzh-ch/elasticluster/commit/8be18f8978d1852aa65f2114a82048770a8a82b1>

Thanks a lot for your patience and for testing the fix!
