### ISSUE TITLE
'NoneType' object has no attribute 'headers' error when using libcloud and the OpenStack provider

### ISSUE THREAD

**Issue by miltondp** [gc3-uzh-ch/elasticluster#458]
I'm trying to use Elasticloud with libcloud and the OpenStack provider. This is my configuration file:

```
[cloud/my_cloud]
provider=libcloud
driver_name=openstack
ex_force_auth_url=$OS_AUTH_URL/tokens
username=$OS_USERNAME
password=$OS_PASSWORD
ex_force_auth_version=2.0_password
ex_tenant_name=$OS_TENANT_NAME
ex_force_service_region=regionOne

[login/ubuntu]
image_user=ubuntu
image_user_sudo=root
image_sudo=True
user_key_name=key_instances
user_key_private=~/.ssh/key_instances
user_key_public=~/.ssh/key_instances.pub

[setup/my-slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_worker

[cluster/my]
cloud=my_cloud
login=ubuntu
setup=my-slurm
security_group=default
image_id=3c4c6ac3-2723-48c6-89b6-9510878b17ea
flavor=es1.small
frontend_nodes=1
compute_nodes=1
ssh_to=frontend
```

When I run `elasticluster start my`, I get this error:

```
Starting cluster `bionimbus` with:
* 1 frontend nodes.
* 1 compute nodes.
(This may take a while...)
2017-07-14 15:21:22 bionimbus-pdc.opensciencedatacloud.org gc3.elasticluster[5253] ERROR Could not start node `frontend001`: 'NoneType' object has no attribute 'headers' -- <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/home/miltonpividori/software/elasticluster/elasticluster/cluster.py", line 493, in _start_node
    node.start()
  File "/home/miltonpividori/software/elasticluster/elasticluster/cluster.py", line 1085, in start
    **self.extra)
  File "/home/miltonpividori/software/elasticluster/elasticluster/providers/libcloud_provider.py", line 72, in start_instance
    options.get('image_user_password'))
  File "/home/miltonpividori/software/elasticluster/elasticluster/providers/libcloud_provider.py", line 147, in __prepare_key_pair
    if key_name in [k.name for k in list_key_pairs()]:
  File "/home/miltonpividori/software/elasticluster_env/lib/python2.7/site-packages/libcloud/compute/drivers/openstack.py", line 1894, in list_key_pairs
    response = self.connection.request('/os-keypairs')
  File "/home/miltonpividori/software/elasticluster_env/lib/python2.7/site-packages/libcloud/common/openstack.py", line 227, in request
    raw=raw)
  File "/home/miltonpividori/software/elasticluster_env/lib/python2.7/site-packages/libcloud/common/base.py", line 641, in request
    response = responseCls(**kwargs)
  File "/home/miltonpividori/software/elasticluster_env/lib/python2.7/site-packages/libcloud/compute/drivers/openstack.py", line 1021, in __init__
    super(OpenStack_1_1_Response, self).__init__(*args, **kwargs)
  File "/home/miltonpividori/software/elasticluster_env/lib/python2.7/site-packages/libcloud/common/base.py", line 149, in __init__
    self.headers = lowercase_keys(dict(response.headers))
AttributeError: 'NoneType' object has no attribute 'headers'
2017-07-14 15:21:23 bionimbus-pdc.opensciencedatacloud.org gc3.elasticluster[5253] ERROR Could not start node `compute001`: 'NoneType' object has no attribute 'split' -- <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/home/miltonpividori/software/elasticluster/elasticluster/cluster.py", line 493, in _start_node
    node.start()
  File "/home/miltonpividori/software/elasticluster/elasticluster/cluster.py", line 1085, in start
    **self.extra)
  File "/home/miltonpividori/software/elasticluster/elasticluster/providers/libcloud_provider.py", line 93, in start_instance
    populated_list = self.__get_name_or_id(options[key], list_fn())
  File "/home/miltonpividori/software/elasticluster/elasticluster/providers/libcloud_provider.py", line 244, in __get_name_or_id
    for element in [e.strip() for e in values.split(',')]:
AttributeError: 'NoneType' object has no attribute 'split'
Configuring the cluster.
(this too may take a while...)
Your cluster is ready!

Cluster name:     bionimbus
Cluster template: bionimbus
Default ssh to node: frontend001
- frontend nodes: 1
- compute nodes: 1

To login on the frontend node, run the command:

    elasticluster ssh bionimbus

To upload or download files to the cluster, use the command:

    elasticluster sftp bionimbus
```

However, when I open IPython and try to make a connection and get the key pairs, everything works correctly:

```
In [1]: import os
In [2]: from libcloud.compute.types import Provider
In [3]: from libcloud.compute.providers import get_driver
In [4]: OpenStack = get_driver(Provider.OPENSTACK)
In [5]: driver = OpenStack(os.environ['OS_USERNAME'], os.environ['OS_PASSWORD'], ex_force_auth_url= os.environ['OS_AUTH_URL'] + 'tokens', ex_force_auth_version='2.0_password', ex_force_service_region = 'regionOne', ex_tenant_name = os.environ['OS_TENANT_NAME'])

In [6]: for node in driver.list_nodes():
   ...:     print(node)
   ...:
<Node: uuid=bf226f3b42fe6ac6d9bce32df770ff7800c5d827, name=test01, state=RUNNING, public_ips=[], private_ips=[u'172.16.155.28'], provider=OpenStack ...>
In [7]: for kp in driver.list_key_pairs():
   ...:     print(kp)
   ...:
<KeyPair name=key_instances fingerprint=25:e2:08:3e:56:9d:7a:80:69:08:85:1c:e9:a4:a6:43 driver=OpenStack>
```

**Comment by riccardomurri** [comment]
hi Milton, thanks for reporting!  The `libcloud` backend is rather new so there are still some rough edges...

@witlox can you please take a look at this issue?

**Comment by witlox** [comment]
Hi @miltondp, thank you for reporting this issue with libcloud, could you try to remove the following from your config file:

username=$OS_USERNAME
password=$OS_PASSWORD
ex_tenant_name=$OS_TENANT_NAME
ex_force_auth_url=$OS_AUTH_URL/tokens

If this works, we know where the problem is, if not I need to dig a bit deeper.

@riccardomurri do we support using environment variables in the config file?

**Comment by riccardomurri** [comment]
> @riccardomurri do we support using environment variables in the config file?

Yes, using Python's [`os.path.expandvars`](https://docs.python.org/2/library/os.path.html#os.path.expandvars)

**Comment by miltondp** [comment]
Hi @witlox. I tried that by removing those four lines, but it fails with this error:
```bash
$ elasticluster start my
2017-08-15 09:41:06 bionimbus-pdc.opensciencedatacloud.org gc3.elasticluster[15122] ERROR Error: __new__() takes at least 2 arguments (1 given)
Aborting because of errors: __new__() takes at least 2 arguments (1 given).
```

**Comment by riccardomurri** [comment]
Hello @miltondp ,

First the good news: it seems that the problem stems from libcloud having changed the signature of a function, which now takes an additional argument so this should be relatively easy to fix.

Still, we are wondering why did you choose the libcloud driver to connect to OpenStack, instead of using ElastiCluster's native OpenStack interface? (Genuinely curious!)

**Comment by miltondp** [comment]
Hi, @riccardomurri, thank you very much guys for your help and this project.

I'm glad you asked me that :) According to the support guys of the cloud I'm using, they only support libcloud, since you are using Neutron networking (right?) and that's not supported by them. Although they want to upgrade the cloud to support Neutron, there is no end date as to when that would happen. So, I have to stick to libcloud. Does this make sense?

So, after fixing how you call that libcloud function, this would work, right? If so, let me know if you want me to try it.

Thank you!

**Comment by riccardomurri** [comment]
> I'm glad you asked me that :) According to the support guys of the
> cloud I'm using, they only support libcloud, since you are using
> Neutron networking (right?) and that's not supported by them. Although
> they want to upgrade the cloud to support Neutron, there is no end
> date as to when that would happen. So, I have to stick to
> libcloud. Does this make sense?

Makes total sense.  This is definitely a use case we didn't think of
before.  Thanks for reporting!

Technically, though, whether ElastiCluster uses Neutron depends on the
version of the OpenStack client installed: if you have
`python-novaclient < 8.0.0` then ElastiCluster tries to do everything
through the "novaclient" library; if you have a later version of
`python-novaclient`, then the networking functions are no longer
available in "novaclient" and we must use "neutronclient".  (I am not
sure older versions of `python-novaclient` are still installable though,
given the forest of dependencies that OpenStack libraries have...)

**Comment by riccardomurri** [comment]
hi @miltondp I just merged the fix that @witlox submitted in PR #477 -- can you please test the code in the latest "master" branch and tell us if it works?

**Comment by miltondp** [comment]
Great news! Sure, give me a couple of days and I will try it. Thank you very much!

**Comment by miltondp** [comment]
Hi, guys. Sorry for the delay in trying this fix.
I got the latest changes in master, but I'm getting the same error:

```
/home/miltonpividori/software/elasticluster_env2/local/lib/python2.7/site-packages/libcloud/utils/py3.py:76: UserWarning: Missing backports.ssl_match_hostname package
  warnings.warn("Missing backports.ssl_match_hostname package")
Starting cluster `bionimbus` with:
* 1 frontend nodes.
* 1 compute nodes.
(This may take a while...)
2017-09-21 15:20:13 bionimbus-pdc.opensciencedatacloud.org gc3.elasticluster[21590] ERROR Could not start node `compute001`: 'NoneType' object has no attribute 'headers' -- <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/home/miltonpividori/software/elasticluster/elasticluster/cluster.py", line 499, in _start_node
    node.start()
  File "/home/miltonpividori/software/elasticluster/elasticluster/cluster.py", line 1141, in start
    **self.extra)
  File "/home/miltonpividori/software/elasticluster/elasticluster/providers/libcloud_provider.py", line 110, in start_instance
    options.get('image_user_password'))
  File "/home/miltonpividori/software/elasticluster/elasticluster/providers/libcloud_provider.py", line 186, in __prepare_key_pair
    if key_name in [k.name for k in list_key_pairs()]:
  File "/home/miltonpividori/software/elasticluster_env2/local/lib/python2.7/site-packages/libcloud/compute/drivers/openstack.py", line 1892, in list_key_pairs
    response = self.connection.request('/os-keypairs')
  File "/home/miltonpividori/software/elasticluster_env2/local/lib/python2.7/site-packages/libcloud/common/openstack.py", line 223, in request
    raw=raw)
  File "/home/miltonpividori/software/elasticluster_env2/local/lib/python2.7/site-packages/libcloud/common/base.py", line 637, in request
    response = responseCls(**kwargs)
  File "/home/miltonpividori/software/elasticluster_env2/local/lib/python2.7/site-packages/libcloud/compute/drivers/openstack.py", line 1019, in __init__
    super(OpenStack_1_1_Response, self).__init__(*args, **kwargs)
  File "/home/miltonpividori/software/elasticluster_env2/local/lib/python2.7/site-packages/libcloud/common/base.py", line 145, in __init__
    self.headers = lowercase_keys(dict(response.headers))
AttributeError: 'NoneType' object has no attribute 'headers'
2017-09-21 15:20:13 bionimbus-pdc.opensciencedatacloud.org gc3.elasticluster[21590] ERROR Could not start node `frontend001`: 'NoneType' object has no attribute 'split' -- <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/home/miltonpividori/software/elasticluster/elasticluster/cluster.py", line 499, in _start_node
    node.start()
  File "/home/miltonpividori/software/elasticluster/elasticluster/cluster.py", line 1141, in start
    **self.extra)
  File "/home/miltonpividori/software/elasticluster/elasticluster/providers/libcloud_provider.py", line 132, in start_instance
    populated_list = self.__get_name_or_id(options[key], list_fn())
  File "/home/miltonpividori/software/elasticluster/elasticluster/providers/libcloud_provider.py", line 283, in __get_name_or_id
    for element in [e.strip() for e in values.split(',')]:
AttributeError: 'NoneType' object has no attribute 'split'
Configuring the cluster.
(this too may take a while...)
2017-09-21 15:20:14 bionimbus-pdc.opensciencedatacloud.org gc3.elasticluster[21590] WARNING Ignoring node `frontend001`: No IP address.
2017-09-21 15:20:14 bionimbus-pdc.opensciencedatacloud.org gc3.elasticluster[21590] WARNING Ignoring node `compute001`: No IP address.
Your cluster is ready!

Cluster name:     bionimbus
Cluster template: bionimbus
Default ssh to node: frontend001
- frontend nodes: 1
- compute nodes: 1

To login on the frontend node, run the command:

    elasticluster ssh bionimbus

To upload or download files to the cluster, use the command:

    elasticluster sftp bionimbus
```
