### ISSUE TITLE
use of custom image with GCE

### ISSUE THREAD

**Issue by laurapoggio-sptools** [gc3-uzh-ch/elasticluster#462]
I am trying to use a custom image to create a cluster with gridengine on GCE. at the bottom my config file. It works perfectly if I use the standard centos image from GCE. If I use my image I get the error below:

```
2017-07-25 10:40:28 elasti gc3.elasticluster[5135] ERROR Error creating instance `<HttpError 403 when requesting https://www.googleapis.com/compute/v1/projects/*****/zones/europe-west1-b/instances?alt=json returned "Required 'compute.images.useReadOnly' permission for 'projects/test-cloud/global/images/myimage'">`                                                                             
2017-07-25 10:40:28 elasti gc3.elasticluster[5135] ERROR Could not start node `frontend001`: Error creating instance `<HttpError 403 when requesting https://www.googleapis.com/compute/v1/projects/*****/zones/europe-west1-b/instances?alt=json returned "Required 'compute.images.useReadOnly' permission for 'projects/test-cloud/global/images/myimage'">` -- <class 'elasticluster.exceptions.InstanceError'>                                                                                                                                                                                                 
Traceback (most recent call last):
  File "/home/user/bin/elasti/src/elasticluster/cluster.py", line 493, in _start_node
    node.start()
  File "/home/user/bin/elasti/src/elasticluster/cluster.py", line 1085, in start
    **self.extra)
  File "/home/user/bin/elasti/src/elasticluster/providers/gce.py", line 364, in start_instance
    raise InstanceError("Error creating instance `%s`" % e)
InstanceError: Error creating instance `<HttpError 403 when requesting https://www.googleapis.com/compute/v1/projects/*****/zones/europe-west1-b/instances?alt=json returned "Required 'compute.images.useReadOnly' permission for 'projects/test-cloud/global/images/myimage'">
```
Any suggestions on how to use a custom image with elasticluster would be really welcomed as it can take up to 3/4 hours to install all the softwares (some of them are from source) needed in this configurations.

Thanks

```
[cloud/google]
provider=google
gce_client_id=*****
gce_client_secret=*****
gce_project_id=*****
zone=europe-west1-b
noauth_local_webserver=True

[login/google-login]
image_user=user
image_user_sudo=root
image_sudo=True
user_key_name=user
user_key_private=~/.ssh/google_compute_engine
user_key_public=~/.ssh/google_compute_engine.pub

[setup/ansible-gridengine]
provider=ansible
frontend_groups=gridengine_master
compute_groups=gridengine_worker

[cluster/gridengine]
cloud=google
login=google-login
setup=ansible-gridengine
security_group=default
image_id=myimage
flavor=n1-standard-1
frontend_nodes=1
compute_nodes=2
image_userdata=
ssh_to=frontend

```

**Comment by riccardomurri** [comment]
hello @laurapoggio-sptools -- to me, this looks like the [same problem that @rnaplus reported on the ElastiCluster mailing list][1] a few days ago, and has since found a solution:

> The custom image is working now. *[...]* The solution was to use the selfLink URL instead of the image name.

Does this help?

[1]: https://groups.google.com/d/msg/elasticluster/1plUe6Q1Jz4/1ZdxuLGcEgAJ

**Comment by laurapoggio-sptools** [comment]
Thanks a lot. Using the selfLink URL instead of the image name solved the problem.
Thanks

**Comment by riccardomurri** [comment]
All's well that ends well :-)
