### ISSUE TITLE
Centos7, python 2.7 openstack API v3

### ISSUE THREAD

**Issue by maikenp** [gc3-uzh-ch/elasticluster#469]
Hi, 
I successfully managed to set up elasticluster on centos6, using python 2.7 and with openstack API v3. 

Now I would like to try on centos7 with python 2.7 and openstack api v3. 

Configuration is quoted below. Contains exactly the same as for my recent setup. 
I am using elasticluster downloaded from 
git clone git://github.com/gc3-uzh-ch/elasticluster.git src
to get the newest version. 

This is what happens 
```
(elasticluster)[centos@elasticluster-test ~]$ elasticluster -vvv start slurm -n testcluster
/home/centos/elasticluster/lib/python2.7/site-packages/libcloud/utils/py3.py:76: UserWarning: Missing backports.ssl_match_hostname package
  warnings.warn("Missing backports.ssl_match_hostname package")
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG Checking section `cluster/slurm` ...
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG Checking section `login/centos` ...
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG Checking section `setup/ansible-slurm` ...
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG Checking section `cloud/iaas` ...
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG Using class <class 'elasticluster.providers.openstack.OpenStackCloudProvider'> from module <module 'elasticluster.providers.openstack' from '/home/centos/elasticluster/src/elasticluster/providers/openstack.pyc'> to instanciate provider 'openstack'
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG Using OpenStack Identity API v3 because of `/v3` ending in auth URL; set environmental variable OS_IDENTITY_API_VERSION to force use of Identity API v2 instead.
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG Using class <class 'elasticluster.providers.ansible_provider.AnsibleSetupProvider'> from module <module 'elasticluster.providers.ansible_provider' from '/home/centos/elasticluster/src/elasticluster/providers/ansible_provider.pyc'> to instanciate provider 'ansible'
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG setting variable multiuser_cluster=no for node kind compute
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG setting variable multiuser_cluster=no for node kind frontend
Starting cluster `testcluster` with:
* 1 frontend nodes.
* 1 compute nodes.
(This may take a while...)
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] INFO Starting cluster nodes ...
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG Created pool of 2 threads
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG _start_node: working on node `frontend001`
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] INFO Starting node frontend001 ...
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] INFO Using Keystone API v3 session to authenticate to OpenStack
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG _start_node: working on node `compute001`
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] INFO Starting node compute001 ...
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] INFO Using Keystone API v3 session to authenticate to OpenStack
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG Checking keypair `cloud` ...
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] WARNING UserWarning: Unable to check key file `/home/centos/.ssh/cloud.key` because it is encrypted with a password. Please, ensure that you added it to the SSH agent with `ssh-add /home/centos/.ssh/cloud.key`
2017-08-01 12:05:13 elasticluster-test gc3.elasticluster[22245] DEBUG Checking keypair `cloud` ...
2017-08-01 12:07:20 elasticluster-test gc3.elasticluster[22245] ERROR Could not start node `compute001`: Unable to establish connection to https://api.uh-iaas.no:5000/v3/auth/tokens: HTTPSConnectionPool(host='api.uh-iaas.no', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8058148b50>: Failed to establish a new connection: [Errno 110] Connection timed out',)) -- <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
Traceback (most recent call last):
  File "/home/centos/elasticluster/src/elasticluster/cluster.py", line 493, in _start_node
    node.start()
  File "/home/centos/elasticluster/src/elasticluster/cluster.py", line 1085, in start
    **self.extra)
  File "/home/centos/elasticluster/src/elasticluster/providers/openstack.py", line 316, in start_instance
    self._check_keypair(key_name, public_key_path, private_key_path)
  File "/home/centos/elasticluster/src/elasticluster/providers/openstack.py", line 485, in _check_keypair
    keypair = self.nova_client.keypairs.get(name)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/novaclient/api_versions.py", line 393, in substitution
    return methods[-1].func(obj, *args, **kwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/novaclient/v2/keypairs.py", line 74, in get
    "keypair")
  File "/home/centos/elasticluster/lib/python2.7/site-packages/novaclient/base.py", line 351, in _get
    resp, body = self.api.client.get(url)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 288, in get
    return self.request(url, 'GET', **kwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/novaclient/client.py", line 77, in request
    **kwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 447, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 192, in request
    return self.session.request(url, method, **kwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/positional/__init__.py", line 108, in inner
    return wrapped(*args, **kwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 578, in request
    auth_headers = self.get_auth_headers(auth)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 905, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/plugin.py", line 90, in get_headers
    token = self.get_token(session)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 89, in get_token
    return self.get_access(session).auth_token
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 135, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/v3/base.py", line 167, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 853, in post
    return self.request(url, 'POST', **kwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/positional/__init__.py", line 108, in inner
    return wrapped(*args, **kwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 703, in request
    resp = send(**kwargs)
  File "/home/centos/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 777, in _send_request
    raise exceptions.ConnectFailure(msg)
ConnectFailure: Unable to establish connection to https://api.uh-iaas.no:5000/v3/auth/tokens: HTTPSConnectionPool(host='api.uh-iaas.no', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8058148b50>: Failed to establish a new connection: [Errno 110] Connection timed out',))

```

```
[cloud/iaas]
provider=openstack
auth_url=https://api.uh-iaas.no:5000/v3
username=maiken.pedersen@usit.uio.no
password=xxxxxxx
project_name=uio-test-hpc-grid
user_domain_name=dataporten
project_domain_name=dataporten

[login/centos]
image_user=centos
image_user_sudo=root
image_sudo=True
user_key_name=cloud
user_key_private=~/.ssh/cloud.key
user_key_public=~/.ssh/cloud.key.pub

[setup/ansible-slurm]
provider=ansible
frontend_groups=slurm_master,ganglia_master,ganglia_monitor
compute_groups=slurm_worker,ganglia_monitor
global_var_multiuser_cluster=no

[cluster/slurm]
cloud=iaas
login=centos
setup=ansible-slurm
security_group=default
image_id=78d0cd24-8607-4e58-823a-8b16ee851e7a
frontend_nodes=1
compute_nodes=1
ssh_to=frontend
network_ids=c97fa886-592e-4ad1-a995-6d55651bed78

[cluster/slurm/frontend]
flavor=m1.small

[cluster/slurm/compute]
flavor=m1.large
```

**Comment by maikenp** [comment]
Closing this issue as it turned out to be our cloud providers not having set up firewall correctly.
