### ISSUE TITLE
problem booting a cluster in AWS. flavor option is ignored

### ISSUE THREAD

**Issue by pescobar** [gc3-uzh-ch/elasticluster#481]
Hi,

I am testing the latest code in master branch to boot a cluster in AWS but I get an error.

This is my config file:

```
[cloud/amazon-eu-west-1]
provider=ec2_boto
ec2_url=https://ec2.eu-west-1.amazonaws.com
ec2_access_key=XXXXXX
ec2_secret_key=YYYYY
ec2_region=eu-west-1
request_floating_ip=False

[login/centos]
image_user=centos
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/id_rsa
user_key_public=~/.ssh/id_rsa.pub

[setup/ansible-slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_worker

[cluster/slurm_centos7]
cloud=amazon-eu-west-1
login=centos
setup=ansible-slurm
security_group=elasticluster
image_id=ami-061b1560
flavor=t2.small
frontend_nodes=1
compute_nodes=2
ssh_to=frontend

[cluster/slurm_centos7/compute]
flavor=t2.small
```

but when I try to boot the cluster I get these errors:

```2017-08-22 10:21:36 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[3650] ERROR Apparently, Amazon does not compute the RSA key fingerprint as we do! We cannot check if the uploaded keypair is correct!```

```
2017-08-22 10:21:37 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[3650] ERROR Error starting instance: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type.</Message></Error></Errors><RequestID>2307ce60-0268-40ac-8d54-50eb4762e982</RequestID></Response>
```

Looking for that error message I found this post in stackoverflow https://stackoverflow.com/a/33595810/7241633 which suggest that maybe elasticluster is ignoring the `flavor` option and trying to use the default flavor `t2.micro` which doesn't support HVM virtualization. Does it makes sense or am I doing something wrong in my config file?

**Comment by riccardomurri** [comment]
It would be my guess, too, that there is a mismatch between `image_id` and `flavor` (i.e., instance type)

I am not sure if this is a problem in ElastiCluster, though -- how could it possibly know that ""Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type"?

**Comment by pescobar** [comment]
right now the machine that I am using to execute elasticluster in AWS (booted from the AWS webui) is using ami `ami-061b1560` (centos7) and instance type `t2.small` so the combination of those two seem to work.

My guess is that elasticluster is trying to boot `ami-061b1560` with the default instance type `t2.micro` which doesn't support HVM. Is that possible? I tried to boot with `-vvvvvvv` but I don't get those details in the debug log.

**Comment by riccardomurri** [comment]
I've just made the code in "master" more chatty about what image/flavor it is starting nodes with.  Can you please try again and post the DEBUG level logs?

(BTW, the web page https://aws.amazon.com/marketplace/pp/B00O7WM7QW lists `t2.micro` as an option -- look in the box at the bottom of the right column)

**Comment by pescobar** [comment]
thanks for your quick response @riccardomurri . It seems that elasticluster is ignoring the `flavour` section from the config. No matter what flavour I use in the config file elasticluster always uses `m1.small`. In the config I tried `flavor=m3.large` and `flavor=t2.small` but I always get this in the debug log:

```
2017-08-22 15:51:56 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[16918] INFO Starting cluster nodes ...
2017-08-22 15:51:56 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[16918] DEBUG _start_node: working on node `frontend001`
2017-08-22 15:51:56 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[16918] INFO Starting node `frontend001` from image `ami-061b1560` with flavor m1.small ...
2017-08-22 15:51:56 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[16918] DEBUG Connecting to ec2 host ec2.eu-west-1.amazonaws.com
2017-08-22 15:51:56 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[16918] DEBUG EC2 connection has been successful.
2017-08-22 15:51:56 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[16918] DEBUG Checking keypair `elasticluster`.
2017-08-22 15:51:56 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[16918] ERROR Apparently, Amazon does not compute the RSA key fingerprint as we do! We cannot check if the uploaded keypair is correct!
2017-08-22 15:51:56 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[16918] DEBUG Checking security group `elasticluster`.
2017-08-22 15:51:56 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[16918] ERROR Error starting instance: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type.</Message></Error></Errors><RequestID>80dcfef3-f95e-445b-b3d2-c72eacfbbe37</RequestID></Response>
2017-08-22 15:51:56 ip-172-31-27-41.eu-west-1.compute.internal gc3.elasticluster[16918] ERROR Could not start node `frontend001`: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type.</Message></Error></Errors><RequestID>80dcfef3-f95e-445b-b3d2-c72eacfbbe37</RequestID></Response> -- <class 'elasticluster.exceptions.InstanceError'>
Traceback (most recent call last):
  File "/home/centos/venv-elasticluster/src/elasticluster/cluster.py", line 493, in _start_node
    node.start()
  File "/home/centos/venv-elasticluster/src/elasticluster/cluster.py", line 1086, in start
    **self.extra)
  File "/home/centos/venv-elasticluster/src/elasticluster/providers/ec2_boto.py", line 267, in start_instance
    raise InstanceError(ex)
InstanceError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type.</Message></Error></Errors><RequestID>80dcfef3-f95e-445b-b3d2-c72eacfbbe37</RequestID></Response>
```

For this account I have provided full access to EC2 but I have also tried to use a different AWS account to double check if it could be a permissions problem and I also get the same error.

**Comment by riccardomurri** [comment]
I cannot reproduce this: the `flavor=` option is read correctly in my tests.

However, ElastiCluster has some perhaps counter-intuitive behavior here: once a cluster is started, even if the start is not successful, the flavor and image ID of all nodes are saved in the "storage" and changes to the configuration file are ignored.  Could this be your case?  What happens if you completely delete the cluster (`elasticlsuter stop -y cluster_name`) and then start it again?

**Comment by pescobar** [comment]
ouch!! deleting the contents of `~/.elasticluster/storage/` solved the issue :| Sorry @riccardomurri for make you lose your time for such a stupid mistake !!

To get something positive from this issue, I would suggest that elasticluster prints by default something like `loading the cluster configuration from /path/to/used/config` . Maybe providing this information to users can avoid this kind of mistakes in the future.

Thanks again for your great support @riccardomurri and sorry for the trouble.
