### ISSUE TITLE
Problem with elasticluster ssh

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#483]
I see this error when I try to use `elasticluster ssh` to connect to a new cluster:
```
elasticluster ssh c7slurm1
/home/centos/adam/elasticluster/lib/python2.7/site-packages/libcloud/utils/py3.py:76: UserWarning: Missing backports.ssl_match_hostname package
  warnings.warn("Missing backports.ssl_match_hostname package")
2017-08-23 11:14:36 vanloo-test-4-20170817 gc3.elasticluster[5816] WARNING UserWarning: Configuration key `setup_provider` in section `cluster/slurm` should be renamed to `setup` -- please update configuration file(s). Support for automatic renaming will be removed in release 2.0 of ElastiCluster.
2017-08-23 11:14:36 vanloo-test-4-20170817 gc3.elasticluster[5816] WARNING FutureWarning: OpenStack user domain name is present both in the environment and the config file. Environment variable OS_USER_DOMAIN_NAME takes precedence, but this may change in the future.
2017-08-23 11:14:36 vanloo-test-4-20170817 gc3.elasticluster[5816] WARNING FutureWarning: OpenStack password is present both in the environment and the config file. Environment variable OS_PASSWORD takes precedence, but this may change in the future.
2017-08-23 11:14:36 vanloo-test-4-20170817 gc3.elasticluster[5816] WARNING UserWarning: Environment variable OS_NETWORK_API_VERSION set, but ElastiCluster does not supporting selecting the OpenStack Networking API (Neutron) version yet.
2017-08-23 11:14:37 vanloo-test-4-20170817 gc3.elasticluster[5816] ERROR Error: global name 'parse_ip_address_and_port' is not defined
Aborting because of errors: global name 'parse_ip_address_and_port' is not defined.
```

This is on CentOS 7, with a SLURM cluster.

Manual SSH to the nodes works fine.

**Comment by riccardomurri** [comment]
Can you please try again with the latest "master"? Should have been fixed in e166932

**Comment by verdurin** [comment]
New error now:
```
gc3.elasticluster[6025] ERROR Error: sequence item 8: expected string, int found
Aborting because of errors: sequence item 8: expected string, int found.
```

**Comment by riccardomurri** [comment]
Can you post a full traceback?

**Comment by verdurin** [comment]
It doesn't traceback anymore...

**Comment by riccardomurri** [comment]
I have pushed a few commits to "master" that may (or may not) help.  Can you pls test them?

**Comment by verdurin** [comment]
Still the same error, I'm afraid. No traceback.

**Comment by riccardomurri** [comment]
It's weird that you get no tracebacks... are you using `elasticluster -vvvv ssh ...` ?

**Comment by verdurin** [comment]
Here you go with the extra logging:
```
 gc3.elasticluster[6588] ERROR Error: sequence item 8: expected string, int found
Traceback (most recent call last):
  File "/home/centos/adam/elasticluster/src/elasticluster/__main__.py", line 195, in main
    return self.params.func()
  File "/home/centos/adam/elasticluster/src/elasticluster/subcommands.py", line 81, in __call__
    return self.execute()
  File "/home/centos/adam/elasticluster/src/elasticluster/subcommands.py", line 694, in execute
    log.debug("Running command `%s`" % str.join(' ', ssh_cmdline))
TypeError: sequence item 8: expected string, int found
Aborting because of errors: sequence item 8: expected string, int found.
```

**Comment by riccardomurri** [comment]
Should be fixed, pls try again with latest "master"

**Comment by verdurin** [comment]
Yes, that works. Thanks again...
