### ISSUE TITLE
OS_xxx environnement variables not read

### ISSUE THREAD

**Issue by jehane** [gc3-uzh-ch/elasticluster#496]
I want to use the cloud/openstack provider to start clusters but the OS_xxx environnement variables are not used by elasticluster
so my OS_DOMAIN_PROJECT_NAME is set to 'Default' instead of our custom value and authentication on Keystone are failing. 
Using openstack command-line client in the elasticluster virtualenv work. 
I'm using elasticluster version 1.3.dev0

**Comment by jehane** [comment]
debug trace : 
 elasticluster -vvv start slurm-on-ubuntu16 
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Checking section `cluster/slurm-on-ubuntu16` ...
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Checking section `login/ubuntu` ...
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Checking section `setup/slurm` ...
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Checking section `cloud/openstack` ...
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Using class <class 'elasticluster.providers.ansible_provider.AnsibleSetupProvider'> from module <module 'elasticluster.providers.ansible_provider' from '/home/mlombard/elasticluster/src/elasticluster/providers/ansible_provider.pyc'> to instanciate provider 'ansible'
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG setting variable ansible_python_interpreter=/usr/bin/python2.7 for node kind master
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG setting variable ansible_python_interpreter=/usr/bin/python2.7 for node kind worker
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Using class <class 'elasticluster.providers.openstack.OpenStackCloudProvider'> from module <module 'elasticluster.providers.openstack' from '/home/mlombard/elasticluster/src/elasticluster/providers/openstack.pyc'> to instanciate provider 'openstack'
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG OpenStack auth URL taken from env variable OS_AUTH_URL
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG OpenStack user name taken from env variable OS_USERNAME
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG OpenStack user domain name taken from env variable OS_USER_DOMAIN_NAME
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG OpenStack password taken from env variable OS_PASSWORD
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG **OpenStack project name taken from env variable OS_PROJECT_NAME**
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG OpenStack region_name taken from env variable OS_REGION_NAME
Starting cluster `slurm-on-ubuntu16` with:
* 1 worker nodes.
* 1 master nodes.
(This may take a while...)
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] INFO Starting cluster nodes ...
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Created pool of 2 threads
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG _start_node: working on node `worker001`
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG _start_node: working on node `master001`
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] INFO Starting node `worker001` from image `feadc773-3eb7-4a49-9f83-202b1758053e` with flavor m1.small ...
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] INFO Starting node `master001` from image `feadc773-3eb7-4a49-9f83-202b1758053e` with flavor m1.small ...
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='http://193.55.251.41:5000/v3' OS_USERNAME='mlombard' OS_USER_DOMAIN_NAME='saclay' OS_PROJECT_NAME='test-sic' **OS_PROJECT_DOMAIN_NAME='default'** OS_REGION_NAME='RegionOne'
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] INFO Using Keystone API v3 session to authenticate to OpenStack
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='http://193.55.251.41:5000/v3' OS_USERNAME='mlombard' OS_USER_DOMAIN_NAME='saclay' OS_PROJECT_NAME='test-sic' OS_PROJECT_DOMAIN_NAME='default' OS_REGION_NAME='RegionOne'
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] INFO Using Keystone API v3 session to authenticate to OpenStack
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Creating OpenStack Network API (Neutron) client ...
2017-10-11 12:42:02 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Creating OpenStack Network API (Neutron) client ...
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Checking keypair `Marianne` ...
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] DEBUG Checking keypair `Marianne` ...
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] ERROR Could not start node `worker001`: The request you have made requires authentication. (HTTP 401) (Request-ID: req-8aca16da-2f2b-40dc-8632-3d05887b09c8) -- <class 'keystoneauth1.exceptions.http.Unauthorized'>
Traceback (most recent call last):
  File "/home/mlombard/elasticluster/src/elasticluster/cluster.py", line 499, in _start_node
    node.start()
  File "/home/mlombard/elasticluster/src/elasticluster/cluster.py", line 1141, in start
    **self.extra)
  File "/home/mlombard/elasticluster/src/elasticluster/providers/openstack.py", line 398, in start_instance
    self._check_keypair(key_name, public_key_path, private_key_path)
  File "/home/mlombard/elasticluster/src/elasticluster/providers/openstack.py", line 567, in _check_keypair
    keypair = self.nova_client.keypairs.get(name)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/novaclient/api_versions.py", line 393, in substitution
    return methods[-1].func(obj, *args, **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/novaclient/v2/keypairs.py", line 74, in get
    "keypair")
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/novaclient/base.py", line 351, in _get
    resp, body = self.api.client.get(url)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 304, in get
    return self.request(url, 'GET', **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/novaclient/client.py", line 77, in request
    **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 463, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 189, in request
    return self.session.request(url, method, **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 573, in request
    auth_headers = self.get_auth_headers(auth)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 900, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/plugin.py", line 90, in get_headers
    token = self.get_token(session)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 89, in get_token
    return self.get_access(session).auth_token
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 135, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/v3/base.py", line 165, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 848, in post
    return self.request(url, 'POST', **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 737, in request
    raise exceptions.from_response(resp, method, url)
Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-8aca16da-2f2b-40dc-8632-3d05887b09c8)
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] ERROR Could not start node `master001`: The request you have made requires authentication. (HTTP 401) (Request-ID: req-b8e6a98b-0d6e-43b6-83ad-4950b4e53be7) -- <class 'keystoneauth1.exceptions.http.Unauthorized'>
Traceback (most recent call last):
  File "/home/mlombard/elasticluster/src/elasticluster/cluster.py", line 499, in _start_node
    node.start()
  File "/home/mlombard/elasticluster/src/elasticluster/cluster.py", line 1141, in start
    **self.extra)
  File "/home/mlombard/elasticluster/src/elasticluster/providers/openstack.py", line 398, in start_instance
    self._check_keypair(key_name, public_key_path, private_key_path)
  File "/home/mlombard/elasticluster/src/elasticluster/providers/openstack.py", line 567, in _check_keypair
    keypair = self.nova_client.keypairs.get(name)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/novaclient/api_versions.py", line 393, in substitution
    return methods[-1].func(obj, *args, **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/novaclient/v2/keypairs.py", line 74, in get
    "keypair")
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/novaclient/base.py", line 351, in _get
    resp, body = self.api.client.get(url)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 304, in get
    return self.request(url, 'GET', **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/novaclient/client.py", line 77, in request
    **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 463, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 189, in request
    return self.session.request(url, method, **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 573, in request
    auth_headers = self.get_auth_headers(auth)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 900, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/plugin.py", line 90, in get_headers
    token = self.get_token(session)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 89, in get_token
    return self.get_access(session).auth_token
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 135, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/v3/base.py", line 165, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 848, in post
    return self.request(url, 'POST', **kwargs)
  File "/home/mlombard/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 737, in request
    raise exceptions.from_response(resp, method, url)
Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-b8e6a98b-0d6e-43b6-83ad-4950b4e53be7)
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] INFO Checking SSH connection to nodes ...
Configuring the cluster.
(this too may take a while...)
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] WARNING Ignoring node `worker001`: No IP address.
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] WARNING Ignoring node `master001`: No IP address.
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] INFO No inventory file was created.
2017-10-11 12:42:03 mallorne.saclay.inria.fr gc3.elasticluster[24544] INFO No setup required for this cluster.
Your cluster is ready!

Cluster name:     slurm-on-ubuntu16
Cluster template: slurm-on-ubuntu16
Default ssh to node: master001
- worker nodes: 1
- master nodes: 1

To login on the frontend node, run the command:

    elasticluster ssh slurm-on-ubuntu16

To upload or download files to the cluster, use the command:

    elasticluster sftp slurm-on-ubuntu16

**Comment by riccardomurri** [comment]
Can you pls try:

```
elasticluster stop -y slurm-on-ubuntu16
elasticluster -vvv start slurm-on-ubuntu16
```

**Comment by riccardomurri** [comment]
Also please check if there is anything in directory `~/.elasticluster/storage` between the `stop` and `start` commands.  It should be empty; if not, pls remove the files there (unless you have other clusters running).

**Comment by riccardomurri** [comment]
I cannot reproduce the behavior here:

```
$ export OS_PROJECT_DOMAIN_NAME=foobar

$ elasticluster -vvv start su16                                                                                                                                                   [13:10:34]
...
2017-10-11 13:10:40 xenia gc3.elasticluster[3537] DEBUG Using class <class 'elasticluster.providers.openstack.OpenStackCloudProvider'> from module <module 'elasticluster.providers.openstack' from '/home/rmurri/w/elasticluster/elasticluster/providers/openstack.pyc'> to instanciate provider 'openstack'
2017-10-11 13:10:40 xenia gc3.elasticluster[3537] WARNING FutureWarning: OpenStack project domain name is present both in the environment and the config file. Environment variable OS_PROJECT_DOMAIN_NAME takes precedence, but this may change in the future.
2017-10-11 13:10:40 xenia gc3.elasticluster[3537] DEBUG Using OpenStack Identity API v2 because of `/v2.0` ending in auth URL; set environmental variable OS_IDENTITY_API_VERSION to force use of Identity API v3 instead.
Starting cluster `su16` with:
* 1 worker nodes.
* 1 master nodes.
(This may take a while...)
2017-10-11 13:10:40 xenia gc3.elasticluster[3537] INFO Starting cluster nodes ...
2017-10-11 13:10:40 xenia gc3.elasticluster[3537] DEBUG Created pool of 2 threads
2017-10-11 13:10:40 xenia gc3.elasticluster[3537] DEBUG _start_node: working on node `worker001`
2017-10-11 13:10:40 xenia gc3.elasticluster[3537] DEBUG _start_node: working on node `master001`
2017-10-11 13:10:40 xenia gc3.elasticluster[3537] INFO Starting node `worker001` from image `c09bd795-e14a-40e5-a052-75d6bbde8507` with flavor 1cpu-4ram-hpc ...
2017-10-11 13:10:40 xenia gc3.elasticluster[3537] INFO Starting node `master001` from image `c09bd795-e14a-40e5-a052-75d6bbde8507` with flavor 1cpu-4ram-hpc ...
2017-10-11 13:10:40 xenia gc3.elasticluster[3537] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='https://cloud.s3it.uzh.ch:5000/v2.0' OS_USERNAME='rmurri' OS_USER_DOMAIN_NAME='default' OS_PROJECT_NAME='$OS_PROJECT_NAME' OS_PROJECT_DOMAIN_NAME='foobar' OS_REGION_NAME=''
```

as you can see the value of the `OS_PROJECT_DOMAIN_NAME` environment variable propagates correctly down to the code that starts the new VM...

**Comment by riccardomurri** [comment]
Oh, wait... In the log you posted (emphasis as in the original comment):

  gc3.elasticluster[24544] DEBUG **OpenStack project name taken from env variable OS_PROJECT_NAME**

but then:

  gc3.elasticluster[24544] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='http://193.55.251.41:5000/v3' OS_USERNAME='mlombard' OS_USER_DOMAIN_NAME='saclay' OS_PROJECT_NAME='test-sic' **OS_PROJECT_DOMAIN_NAME='default'** OS_REGION_NAME='RegionOne'

the two environmental variables __names__ do not match! first one is `OS_PROJECT_NAME`, 2nd one is `OS_PROJECT_DOMAIN_NAME` -- which looks undefined according to the log lines...

So my guess is that you're simply lacking the `OS_PROJECT_DOMAIN_NAME` env. var. (which could be an OpenStack bug, that it's missing from the `openrc` file; I've had an issue just yesterday that amounted exactly to that.)

**Comment by jehane** [comment]
It's the problem. Working if I edit my openrc file
