### ISSUE TITLE
NameError: global name 'region' is not defined

### ISSUE THREAD

**Issue by n4562** [gc3-uzh-ch/elasticluster#498]
https://github.com/gc3-uzh-ch/elasticluster/blob/ac482e0dd4b950d1a8ff5f837c35511610732154/elasticluster/providers/ec2_boto.py#L139

Tested with the following:

Hello,

I have got the following elasticluster config file:

```
[cloud/amazon-us-west-2]
provider=ec2_boto
ec2_url=https://ec2.us-west-2.amazonaws.com
ec2_access_key=**
ec2_secret_key=**
ec2_region=us-west-2
vpc=vpc-5871fd3f

[login/ubuntu]
image_user=ubuntu
image_sudo=True
user_key_name=key
user_key_private=~/.ssh/id_rsa
user_key_public=~/.ssh/id_rsa.pub

[setup/slurm]
frontend_groups=slurm_master,ganglia_master,ganglia_monitor
compute_groups=slurm_worker,ganglia_monitor
submit_groups=slurm_submit,glusterfs_client
global_var_multiuser_cluster=yes

[cluster/slurm-on-ubuntu-aws]
setup=slurm
frontend_nodes=1
compute_nodes=2
ssh_to=frontend
cloud=amazon-us-west-2
security_group=launch-wizard-4
flavor=t2.micro
image_id=ami-6e1a0117
login=ubuntu
network_ids=subnet-d9798390
```

then running the command:
```
elasticluster -vvv start slurm-on-ubuntu-aws
```

I get the following error:

```
2017-10-16 15:51:00 linux-rozm gc3.elasticluster[1885] DEBUG EC2 connection has been successful.
2017-10-16 15:51:00 linux-rozm gc3.elasticluster[1885] ERROR Error connecting to EC2: global name 'region' is not defined
2017-10-16 15:51:00 linux-rozm gc3.elasticluster[1885] ERROR Error connecting to EC2: global name 'region' is not defined
2017-10-16 15:51:00 linux-rozm gc3.elasticluster[1885] ERROR Error connecting to EC2: global name 'region' is not defined
2017-10-16 15:51:00 linux-rozm gc3.elasticluster[1885] ERROR Could not start node `frontend001`: global name 'region' is not defined -- <type 'exceptions.NameError'>
Traceback (most recent call last):
  File ".../elasticluster/cluster.py", line 499, in _start_node
    node.start()
  File ".../elasticluster/cluster.py", line 1141, in start
    **self.extra)
  File ".../elasticluster/providers/ec2_boto.py", line 197, in start_instance
    connection = self._connect()
  File ".../elasticluster/providers/ec2_boto.py", line 139, in _connect
    path=self._ec2path, region=region)
NameError: global name 'region' is not defined
```

**Comment by riccardomurri** [comment]
Should be fixed in the latest "master" branch, can you please check?

**Comment by n4562** [comment]
update does seem that issue.
But another appears (seems related):
`2017-11-11 09:37:58 linux-rozm gc3.elasticluster[5498] ERROR Could not start node `frontend001`: 'str' object has no attribute 'endpoint' -- <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/home/.../bin/elasticluster/src/elasticluster/cluster.py", line 519, in _start_node
    node.start()
  File "/home/.../bin/elasticluster/src/elasticluster/cluster.py", line 1161, in start
    **self.extra)
  File "/home/.../bin/elasticluster/src/elasticluster/providers/ec2_boto.py", line 196, in start_instance
    connection = self._connect()
  File "/home/.../bin/elasticluster/src/elasticluster/providers/ec2_boto.py", line 138, in _connect
    path=self._ec2path, region=self._region_name)
  File "/home/.../bin/anaconda2/envs/cluster2.7/lib/python2.7/site-packages/boto/__init__.py", line 303, in connect_vpc
    return VPCConnection(aws_access_key_id, aws_secret_access_key, **kwargs)
  File "/home/.../bin/anaconda2/envs/cluster2.7/lib/python2.7/site-packages/boto/ec2/connection.py", line 99, in __init__
    self.region.endpoint, debug,
AttributeError: 'str' object has no attribute 'endpoint'`

**Comment by riccardomurri** [comment]
Hmmm... looks like Boto wants some kind of "region" object instead of a string -- can you please try again with latest "master"?

**Comment by n4562** [comment]
yep, that pretty much fixed it.
I did need an additional fix:

```
diff --git a/elasticluster/providers/ec2_boto.py b/elasticluster/providers/ec2_boto.py
index ca87241..3808262 100644
--- a/elasticluster/providers/ec2_boto.py
+++ b/elasticluster/providers/ec2_boto.py
@@ -140,13 +141,13 @@ class BotoCloudProvider(AbstractCloudProvider):
                 log.debug("VPC connection has been successful.")
 
                 for vpc in vpc_connection.get_all_vpcs():
-                    log.debug("Checking whether %s matches %s/%s" %
-                        (self._vpc, vpc.tags['Name'], vpc.id))
-                    if self._vpc in [vpc.tags['Name'], vpc.id]:
+                    log.debug("Checking whether %s matches %s" %
+                        (self._vpc, vpc.id))
+                    if self._vpc in [vpc.id]:
                         self._vpc_id = vpc.id
                         if self._vpc != self._vpc_id:
                             log.debug("VPC %s matches %s" %
-                                (self._vpc, self._vpc_id))
+                                      (self._vpc, self._vpc_id))
                         break
                 else:
                     raise VpcError('VPC %s does not exist.' % self._vpc)
```


vpc.tags being an empty dict in my case (i.e. threw an error)

**Comment by riccardomurri** [comment]
Can you please try again with the latest "master"?  I have adapted your fix to handle both cases (VPCs with and without a name tag.)

**Comment by riccardomurri** [comment]
I'm assuming this is solved now - please re-open if not.
