### ISSUE TITLE
pathlib error related to Azure

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#500]
Just installed from current `master` and see the following error when I first run `elasticluster`:
```
Traceback (most recent call last):
  File "/home/centos/src/elasticluster/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pathlib2' distribution was not found and is required by azure-datalake-store
```

**Comment by verdurin** [comment]
If I add `pathlib2`, this error appears:
```
Traceback (most recent call last):
  File "/home/centos/src/elasticluster/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'scandir' distribution was not found and is required by pathlib2
```

**Comment by verdurin** [comment]
Then:
```
Traceback (most recent call last):
  File "/home/centos/src/elasticluster/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ipaddress' distribution was not found and is required by cryptography
```

**Comment by verdurin** [comment]
Okay, this is basically causing a cascade of dependencies and is clearly the wrong approach.

**Comment by verdurin** [comment]
With the following changes I was able to run normally:
```
diff --git a/setup.py b/setup.py
index e19f3a1..0192bc4 100755
--- a/setup.py
+++ b/setup.py
@@ -120,6 +120,12 @@ elif python_version == (2, 7):
         # a top-level dependency of ElastiCluster
         'Babel>=2.3.4,!=2.4.0',
         'pbr>=2.0.0,!=2.1.0',
+        'ipaddress', # added for pathlib2
+        'enum34', # added for pathlib2
+        'scandir', # added for pathlib2
+        'pathlib2', # needed for pathlib2
+        'functools32', # added for pathlib2
+        'secretstorage', # added for pathlib2
         '',
     ]
 else:
```
