### ISSUE TITLE
SSL endpoint certificate verify error

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#501]
Trying to use SSL endpoints with `elasticluster` on `CentOS 7`.

This works fine with manual `openstackclient` commands, with `OS_CACERT` pointing at the CA certificate.

With `elasticluster` I see this when I try to start a new cluster:
```
2017-11-07 11:36:58 admin2.novalocal gc3.elasticluster[8029] INFO Starting cluster nodes ...                                                                                                                                      [211/1985]
2017-11-07 11:36:58 admin2.novalocal gc3.elasticluster[8029] DEBUG _start_node: working on node `worker001`
2017-11-07 11:36:58 admin2.novalocal gc3.elasticluster[8029] INFO Starting node `worker001` from image `d8b0ec8f-2a56-432e-ac58-d0dc715d51ed` with flavor m1.medium ...
2017-11-07 11:36:58 admin2.novalocal gc3.elasticluster[8029] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='<API host address>:5000/v3' OS_USERNAME='mhuffman' OS_USER_DOMAIN_NAME='default' OS_PROJECT_NAME='mhuffm
an' OS_PROJECT_DOMAIN_NAME='default' OS_REGION_NAME=''
2017-11-07 11:36:58 admin2.novalocal gc3.elasticluster[8029] INFO Using Keystone API v3 session to authenticate to OpenStack
2017-11-07 11:36:58 admin2.novalocal gc3.elasticluster[8029] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2017-11-07 11:36:58 admin2.novalocal gc3.elasticluster[8029] DEBUG Creating OpenStack Network API (Neutron) client ...
2017-11-07 11:36:58 admin2.novalocal gc3.elasticluster[8029] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2017-11-07 11:36:58 admin2.novalocal gc3.elasticluster[8029] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2017-11-07 11:36:58 admin2.novalocal gc3.elasticluster[8029] DEBUG Checking keypair `elasticluster` ...
2017-11-07 11:36:58 admin2.novalocal gc3.elasticluster[8029] ERROR Could not start node `worker001`: SSL exception connecting to https://<API host address>:5000/v3/auth/tokens: ("bad handshake: Error([('SSL routines', 'ssl3_get_
server_certificate', 'certificate verify failed')],)",) -- <class 'keystoneauth1.exceptions.connection.SSLError'>
Traceback (most recent call last):
  File "/home/centos/src/elasticluster/src/elasticluster/cluster.py", line 499, in _start_node
    node.start()
  File "/home/centos/src/elasticluster/src/elasticluster/cluster.py", line 1141, in start
    **self.extra)
  File "/home/centos/src/elasticluster/src/elasticluster/providers/openstack.py", line 398, in start_instance
    self._check_keypair(key_name, public_key_path, private_key_path)
  File "/home/centos/src/elasticluster/src/elasticluster/providers/openstack.py", line 567, in _check_keypair
    keypair = self.nova_client.keypairs.get(name)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/novaclient/api_versions.py", line 393, in substitution
    return methods[-1].func(obj, *args, **kwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/novaclient/v2/keypairs.py", line 74, in get
    "keypair")
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/novaclient/base.py", line 351, in _get
    resp, body = self.api.client.get(url)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 304, in get
    return self.request(url, 'GET', **kwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/novaclient/client.py", line 77, in request
    **kwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 463, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 189, in request
    return self.session.request(url, method, **kwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 573, in request
    auth_headers = self.get_auth_headers(auth)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 900, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/plugin.py", line 90, in get_headers
    token = self.get_token(session)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 89, in get_token
    return self.get_access(session).auth_token
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 135, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/identity/v3/base.py", line 165, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 848, in post
    return self.request(url, 'POST', **kwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 698, in request
    resp = send(**kwargs)
  File "/home/centos/src/elasticluster/lib/python2.7/site-packages/keystoneauth1/session.py", line 760, in _send_request
    raise exceptions.SSLError(msg)
SSLError: SSL exception connecting to https://<API host address>:5000/v3/auth/tokens: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
```

**Comment by riccardomurri** [comment]
Pull request #503 should fix this -- can you please test it?

I will merge into master when you can confirm it does its job. (Std cert here so no issues with `OS_CACERT`)

**Comment by verdurin** [comment]
As I've documented in #503 I see a different error with these changes.

**Comment by riccardomurri** [comment]
hi @verdurin , I finally had time to try... I can get it to the point where it connects and then fails because I do not have an account:

    gc3.elasticluster[6293] ERROR Could not start node `master001`: The request you have made requires authentication. (HTTP 401) (Request-ID: req-93894417-1779-47e1-9bca-d401a30710ee) -- <class 'keystoneauth1.exceptions.http.Unauthorized'>

This means that the SSL connection works and honors `OS_CACERT` -- i.e., the code should be fine.

I had to mess around considerably to get to this point:

1. Download *both* the certificate of the (intermediate) CA that signed the cloud server's certificate *and* the root CA certificate that signed the intermediate CA's cert.
2. Move both PEM files into a directory `/tmp/ca`
3. Run command `c_rehash /tmp/ca`
4. Set environment variable `OS_CACERT` to `/tmp/ca`.

Skip any of the above steps and you won't be able to connect over SSL.

Can you please confirm that it works for you as well?

**Comment by riccardomurri** [comment]
Also works if steps 2.+3. are replaced by: concatenate all CA certificates into a single file `/tmp/cacert.pem` and then the `OS_CACERT` env variable is pointing to that file.

**Comment by verdurin** [comment]
@riccardomurri - yes, that's what I'd already done. To confirm, I don't need to pull any new code to test?

**Comment by verdurin** [comment]
Anyway, testing now, and it's building a cluster, so the fix works. Many thanks for your persistence...

**Comment by riccardomurri** [comment]
Many thanks for reporting and testing!  (and for the patience in having this fixed...!)

Merged into "master", hence closing this issue.
