### ISSUE TITLE
Newest elasticluster from github - conflicting requests requirements 

### ISSUE THREAD

**Issue by maikenp** [gc3-uzh-ch/elasticluster#566]
Hi, 

I am having problems installing the newest elasticluster as I get conflicts in the requirements: 

Running the elasticluster with setup I get: 

```
Traceback (most recent call last):
  File "/home/centos/elasticluster-06-2018/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/centos/elasticluster-06-2018/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/home/centos/elasticluster-06-2018/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/home/centos/elasticluster-06-2018/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/centos/elasticluster-06-2018/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/centos/elasticluster-06-2018/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/centos/elasticluster-06-2018/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests~=2.14.1' distribution was not found and is required by elasticluster
```

So I do:
```
(elasticluster-06-2018)[centos@elasticluster-final ~]$ pip install 'requests~=2.14.1'
Collecting requests~=2.14.1
  Using cached https://files.pythonhosted.org/packages/e4/b0/286e8a936158e5cc5791d5fa3bc4b1d5a7e1ff4e5b3f3766b63d8e97708a/requests-2.14.2-py2.py3-none-any.whl
msrest 0.5.0 has requirement requests~=2.16, but you'll have requests 2.14.2 which is incompatible.
Installing collected packages: requests
Successfully installed requests-2.14.2
```

But as you  see I get the message
```
msrest 0.5.0 has requirement requests~=2.16, but you'll have requests 2.14.2 which is incompatible.
```
Tips for solving? 

Best wishes
Maiken

**Comment by riccardomurri** [comment]
It looks like there is again a conflict between the OpenStack libraries and the Azure ones... :-/

Can you please try with the latest "master" code?  If it does not work, please post the output of the following command::

    grep 'Requires-Dist: requests' $VIRTUAL_ENV/lib/python2.7/*.dist-info/METADATA
