### ISSUE TITLE
Could not start node `frontend001`: Bad network format: missing 'uuid' (HTTP 400) on OpenStack

### ISSUE THREAD

**Issue by loewa** [gc3-uzh-ch/elasticluster#584]
I have downloaded the latest docker and I am getting the following error:
Could not start node `frontend001`: Bad network format: missing 'uuid' (HTTP 400)
The uuid is in the config file and is valid. What do I have to use for the OpenStack API?

Alex

**Comment by loewa** [comment]
this warning is issued earlier:
WARNING ImportWarning: Not importing directory '/usr/local/lib/python2.7/site-packages/oslo_i18n/locale': missing __init__.py

**Comment by riccardomurri** [comment]
Hello Alex,

that WARNING line is harmless.  Can you please post your configuration file and the exact error message (+ a few lines of context) that you're getting?  To get the DEBUG level log, run `elasticluster` with option `-vvvv`.

**Comment by riccardomurri** [comment]
(Watch out for passwords and other sensitive info -- remove it from the posted file!)

**Comment by loewa** [comment]
ubuntu@deploynode03:~$ ./elasticluster.sh -vvvv start slurm1a
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking section `cluster/slurm1a` ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking section `login/ubuntu` ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking section `setup/slurm1a` ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking section `cloud/openstack` ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Using class <class 'elasticluster.providers.ansible_provider.AnsibleSetupProvider'> from module <module 'elasticluster.providers.ansible_provider' from 'elasticluster/providers/ansible_provider.py'> to instanciate provider 'ansible'
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] WARNING ImportWarning: Not importing directory '/usr/local/lib/python2.7/site-packages/oslo_i18n/locale': missing __init__.py
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Using class <class 'elasticluster.providers.openstack.OpenStackCloudProvider'> from module <module 'elasticluster.providers.openstack' from 'elasticluster/providers/openstack.py'> to instanciate provider 'openstack'
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Using OpenStack Identity API v3 because of `/v3` ending in auth URL; set environmental variable OS_IDENTITY_API_VERSION to force use of Identity API v2 instead.
Starting cluster `slurm1a` with:
* 1 frontend nodes.
* 4 compute nodes.
(This may take a while...)
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] INFO Starting cluster nodes (timeout: 600 seconds) ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Note: starting 5 nodes concurrently.
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG _start_node: working on node `frontend001`
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] INFO Starting node `frontend001` from image `8845410f-5349-40eb-843b-293779b00ea9` with flavor m1.micro ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG _start_node: working on node `compute002`
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] INFO Starting node `compute002` from image `8845410f-5349-40eb-843b-293779b00ea9` with flavor m1.micro ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG _start_node: working on node `compute003`
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='https://identity.optimist.innovo.cloud/v3' OS_USERNAME='hpc_lab' OS_USER_DOMAIN_NAME='default' OS_PROJECT_NAME='optimist-hpc-lab' OS_PROJECT_DOMAIN_NAME='default' OS_REGION_NAME='fra' OS_CACERT='None'
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG _start_node: working on node `compute001`
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] INFO Starting node `compute003` from image `8845410f-5349-40eb-843b-293779b00ea9` with flavor m1.micro ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='https://identity.optimist.innovo.cloud/v3' OS_USERNAME='hpc_lab' OS_USER_DOMAIN_NAME='default' OS_PROJECT_NAME='optimist-hpc-lab' OS_PROJECT_DOMAIN_NAME='default' OS_REGION_NAME='fra' OS_CACERT='None'
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] INFO Starting node `compute001` from image `8845410f-5349-40eb-843b-293779b00ea9` with flavor m1.micro ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='https://identity.optimist.innovo.cloud/v3' OS_USERNAME='hpc_lab' OS_USER_DOMAIN_NAME='default' OS_PROJECT_NAME='optimist-hpc-lab' OS_PROJECT_DOMAIN_NAME='default' OS_REGION_NAME='fra' OS_CACERT='None'
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='https://identity.optimist.innovo.cloud/v3' OS_USERNAME='hpc_lab' OS_USER_DOMAIN_NAME='default' OS_PROJECT_NAME='optimist-hpc-lab' OS_PROJECT_DOMAIN_NAME='default' OS_REGION_NAME='fra' OS_CACERT='None'
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] INFO Using Keystone API v3 session to authenticate to OpenStack
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] INFO Using Keystone API v3 session to authenticate to OpenStack
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG _start_node: working on node `compute004`
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] INFO Using Keystone API v3 session to authenticate to OpenStack
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] INFO Using Keystone API v3 session to authenticate to OpenStack
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] INFO Starting node `compute004` from image `8845410f-5349-40eb-843b-293779b00ea9` with flavor m1.micro ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='https://identity.optimist.innovo.cloud/v3' OS_USERNAME='hpc_lab' OS_USER_DOMAIN_NAME='default' OS_PROJECT_NAME='optimist-hpc-lab' OS_PROJECT_DOMAIN_NAME='default' OS_REGION_NAME='fra' OS_CACERT='None'
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] INFO Using Keystone API v3 session to authenticate to OpenStack
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Network API (Neutron) client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Network API (Neutron) client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Network API (Neutron) client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Network API (Neutron) client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Network API (Neutron) client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking keypair `elasticluster` ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking keypair `elasticluster` ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking keypair `elasticluster` ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking keypair `elasticluster` ...
2018-10-09 15:45:30 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking keypair `elasticluster` ...
2018-10-09 15:45:31 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking existence of security group(s) ['default'] ...
2018-10-09 15:45:31 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking existence of security group(s) ['default'] ...
2018-10-09 15:45:31 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking existence of security group(s) ['default'] ...
2018-10-09 15:45:31 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking existence of security group(s) ['default'] ...
2018-10-09 15:45:31 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Checking existence of security group(s) ['default'] ...
2018-10-09 15:45:32 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Specifying networks for node slurm1a-frontend001:
2018-10-09 15:45:32 ac35c3d5bc20 gc3.elasticluster[1] DEBUG Specifying networks for node slurm1a-compute002:
2018-10-09 15:45:32 ac35c3d5bc20 gc3.elasticluster[1] ERROR Could not start node `frontend001`: Bad network format: missing 'uuid' (HTTP 400) (Request-ID: req-296ca3bb-e0f3-43cf-af5c-60efba709dbc) -- <class 'novaclient.exceptions.BadRequest'>
Traceback (most recent call last):
  File "elasticluster/cluster.py", line 548, in _start_node
    node.start()
  File "elasticluster/cluster.py", line 1171, in start
    **self.extra)
  File "elasticluster/providers/openstack.py", line 505, in start_instance
    vm = self.nova_client.servers.create(node_name, image_id, flavor, **vm_start_args)
  File "/usr/local/lib/python2.7/site-packages/novaclient/v2/servers.py", line 1403, in create
    **boot_kwargs)
  File "/usr/local/lib/python2.7/site-packages/novaclient/v2/servers.py", line 802, in _boot
    return_raw=return_raw, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/novaclient/base.py", line 361, in _create
    resp, body = self.api.client.post(url, body=body)
  File "/usr/local/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 357, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/lib/python2.7/site-packages/novaclient/client.py", line 83, in request
    raise exceptions.from_response(resp, body, url, method)
BadRequest: Bad network format: missing 'uuid' (HTTP 400) (Request-ID: req-296ca3bb-e0f3-43cf-af5c-60efba709dbc)

**Comment by loewa** [comment]
[cluster/slurm1a]
cloud=openstack
login=ubuntu
setup=slurm1a
network_id=8eca090c-d274-44e5-ad7b-71ff70a44a19
security_group=default
# Ubuntu image
image_id=8845410f-5349-40eb-843b-293779b00ea9
flavor=m1.micro
frontend_nodes=1
compute_nodes=4
ssh_to=frontend

[cloud/openstack]
provider=openstack
auth_url=https://identity.optimist.innovo.cloud/v3
username=
password=
project_name=optimist-hpc-lab
region_name=fra

[login/ubuntu]
image_user=ubuntu
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/id_rsa
user_key_public=~/.ssh/id_rsa.pub

[setup/slurm1a]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_worker

**Comment by riccardomurri** [comment]
There seems to be a typo in you config file: it's `network_ids` (with final "s") not `network_id`.  Can you please change it and try again?

**Comment by loewa** [comment]
unfortunately the same message. what is required, the provider net, an internal network? and should the uuid be the network uuid or from the subnet?


2018-10-10 08:34:43 83e1b74e4c10 gc3.elasticluster[1] ERROR Could not start node `compute001`: Bad network format: missing 'uuid' (HTTP 400) (Request-ID: req-aa361c1a-75c5-4d2c-ab82-3ca05289755e) -- <class 'novaclient.exceptions.BadRequest'>
Traceback (most recent call last):
  File "elasticluster/cluster.py", line 548, in _start_node
    node.start()
  File "elasticluster/cluster.py", line 1171, in start
    **self.extra)
  File "elasticluster/providers/openstack.py", line 505, in start_instance
    vm = self.nova_client.servers.create(node_name, image_id, flavor, **vm_start_args)
  File "/usr/local/lib/python2.7/site-packages/novaclient/v2/servers.py", line 1403, in create
    **boot_kwargs)
  File "/usr/local/lib/python2.7/site-packages/novaclient/v2/servers.py", line 802, in _boot
    return_raw=return_raw, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/novaclient/base.py", line 361, in _create
    resp, body = self.api.client.post(url, body=body)
  File "/usr/local/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 357, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/lib/python2.7/site-packages/novaclient/client.py", line 83, in request
    raise exceptions.from_response(resp, body, url, method)
BadRequest: Bad network format: missing 'uuid' (HTTP 400) (Request-ID: req-aa361c1a-75c5-4d2c-ab82-3ca05289755e)

**Comment by loewa** [comment]
Thank you for your patience. I changed it back, but its still rejecting it.
Kind regards,
AL

**Comment by riccardomurri** [comment]
Also watch out: changes in the configuration file are only picked up when you *destroy* the cluster and then start it again.

In other words, if you ever did `elasticluster start slurm1a`, then the configuration for cluster `slurm1a` has been instanciated from the template in the configuration file and won't be updated.  You need to do `elasticluster stop -y slurm1a` (or `rm -v ~/.elasticluster/storage/slurm1a*` though that won't delete VMs), and *then* do `elasticluster start slurm1a` again.

**Comment by loewa** [comment]
Thank you !!!! It works. This was the missing piece.

Kind regards,
Alex

**Comment by riccardomurri** [comment]
All is well that ends well :-)
