### ISSUE TITLE
OpenStack floating IPs not allocated

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#607]
I see the following error with floating IPs on OpenStack Queens:
```
2019-02-14 18:51:16 nvsadmin00.nvs.bmrc.ox.ac.uk gc3.elasticluster[48437] WARNING DeprecationWarning: The addFloatingIP server action API is deprecated as of the 2.44 microversion. This API binding will
 be removed in the first major release after the Nova 16.0.0 Pike release. Use python-neutronclient or openstacksdk instead.
2019-02-14 18:51:16 nvsadmin00.nvs.bmrc.ox.ac.uk gc3.elasticluster[48437] ERROR Could not start node `worker003`: Invalid input for field/attribute address. Value: {u'router_id': None, u'status': u'DOWN
', u'description': u'', u'tags': [], u'tenant_id': u'ab0be65d99634ebd8a08efa95cb5d114', u'created_at': u'2019-02-14T18:41:51Z', u'updated_at': u'2019-02-14T18:41:51Z', u'floating_network_id': u'b8d43b2f
-2cbf-4143-9ad5-7e74e3fe4370', u'fixed_ip_address': None, u'floating_ip_address': u'<IP>', u'revision_number': 0, u'project_id': u'ab0be65d99634ebd8a08efa95cb5d114', u'port_id': None, u'id': u'fa
e4246e-ab35-440b-9681-20070339da22'}. {u'router_id': None, u'status': u'DOWN', u'description': u'', u'tags': [], u'tenant_id': u'ab0be65d99634ebd8a08efa95cb5d114', u'created_at': u'2019-02-14T18:41:51Z'
, u'updated_at': u'2019-02-14T18:41:51Z', u'floating_network_id': u'b8d43b2f-2cbf-4143-9ad5-7e74e3fe4370', u'fixed_ip_address': None, u'floating_ip_address': u'<IP>', u'revision_number': 0, u'pro
ject_id': u'ab0be65d99634ebd8a08efa95cb5d114', u'port_id': None, u'id': u'fae4246e-ab35-440b-9681-20070339da22'} is valid under each of {'format': 'ipv6'}, {'format': 'ipv4'} (HTTP 400) (Request-ID: req
-9e314aba-64b2-43dd-bdb6-43a341f11687) -- <class 'novaclient.exceptions.BadRequest'>
Traceback (most recent call last):
  File "/home/adamh/venvs/elasticluster/src/elasticluster/cluster.py", line 563, in _start_node
    node.start()
  File "/home/adamh/venvs/elasticluster/src/elasticluster/cluster.py", line 1186, in start
    **self.extra)
  File "/home/adamh/venvs/elasticluster/src/elasticluster/providers/openstack.py", line 540, in start_instance
    self._allocate_address(vm, network_ids)
  File "/home/adamh/venvs/elasticluster/src/elasticluster/providers/openstack.py", line 824, in _allocate_address
    instance.add_floating_ip(ip)
  File "/home/adamh/venvs/elasticluster/lib/python2.7/site-packages/novaclient/v2/servers.py", line 193, in add_floating_ip
    return self.manager.add_floating_ip(self, address, fixed_address)
  File "/home/adamh/venvs/elasticluster/lib/python2.7/site-packages/novaclient/api_versions.py", line 393, in substitution
    return methods[-1].func(obj, *args, **kwargs)
  File "/home/adamh/venvs/elasticluster/lib/python2.7/site-packages/novaclient/v2/servers.py", line 940, in add_floating_ip
    return self._action('addFloatingIp', server, {'address': address})
  File "/home/adamh/venvs/elasticluster/lib/python2.7/site-packages/novaclient/v2/servers.py", line 1931, in _action
    info=info, **kwargs)
  File "/home/adamh/venvs/elasticluster/lib/python2.7/site-packages/novaclient/v2/servers.py", line 1942, in _action_return_resp_and_body
    return self.api.client.post(url, body=body)
  File "/home/adamh/venvs/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 357, in post
    return self.request(url, 'POST', **kwargs)
  File "/home/adamh/venvs/elasticluster/lib/python2.7/site-packages/novaclient/client.py", line 83, in request
    raise exceptions.from_response(resp, body, url, method)
BadRequest: Invalid input for field/attribute address. Value: {u'router_id': None, u'status': u'DOWN', u'description': u'', u'tags': [], u'tenant_id': u'ab0be65d99634ebd8a08efa95cb5d114', u'created_at': u'2019-02-14T18:41:51Z', u'updated_at': u'2019-02-14T18:41:51Z', u'floating_network_id': u'b8d43b2f-2cbf-4143-9ad5-7e74e3fe4370', u'fixed_ip_address': None, u'floating_ip_address': u'<IP>', u'revision_number': 0, u'project_id': u'ab0be65d99634ebd8a08efa95cb5d114', u'port_id': None, u'id': u'fae4246e-ab35-440b-9681-20070339da22'}. {u'router_id': None, u'status': u'DOWN', u'description': u'', u'tags': [], u'tenant_id': u'ab0be65d99634ebd8a08efa95cb5d114', u'created_at': u'2019-02-14T18:41:51Z', u'updated_at': u'2019-02-14T18:41:51Z', u'floating_network_id': u'b8d43b2f-2cbf-4143-9ad5-7e74e3fe4370', u'fixed_ip_address': None, u'floating_ip_address': u'<IP>', u'revision_number': 0, u'project_id': u'ab0be65d99634ebd8a08efa95cb5d114', u'port_id': None, u'id': u'fae4246e-ab35-440b-9681-2007
0339da22'} is valid under each of {'format': 'ipv6'}, {'format': 'ipv4'} (HTTP 400) (Request-ID: req-9e314aba-64b2-43dd-bdb6-43a341f11687)
```

Looks like the API has indeed changed.

**Comment by riccardomurri** [comment]
Can you pls check if the code in https://github.com/gc3-uzh-ch/elasticluster/pull/507 fixes the issue?

**Comment by verdurin** [comment]
That branch doesn't apply cleanly to current master:
```
src]$ patch --dry-run -p1 < 507.patch
checking file elasticluster/providers/openstack.py
checking file elasticluster/providers/openstack.py
Hunk #1 FAILED at 830.
Hunk #2 FAILED at 839.
Hunk #3 FAILED at 859.
3 out of 3 hunks FAILED
checking file elasticluster/providers/openstack.py
Hunk #2 FAILED at 851.
1 out of 2 hunks FAILED
checking file elasticluster/conf.py
Hunk #2 succeeded at 666 (offset 3 lines).
checking file elasticluster/providers/openstack.py
Hunk #1 succeeded at 1 with fuzz 2.
Hunk #4 FAILED at 559.
Hunk #5 FAILED at 907.
Hunk #6 FAILED at 942.
3 out of 6 hunks FAILED
checking file elasticluster/providers/openstack.py
Hunk #1 FAILED at 942.
1 out of 1 hunk FAILED
checking file elasticluster/cluster.py
checking file elasticluster/providers/openstack.py
Hunk #1 FAILED at 559.
1 out of 1 hunk FAILED
checking file elasticluster/providers/openstack.py
Hunk #1 succeeded at 560 (offset -25 lines).
checking file elasticluster/providers/openstack.py
Hunk #1 FAILED at 956.
1 out of 1 hunk FAILED
checking file elasticluster/providers/openstack.py
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 965.
2 out of 2 hunks FAILED
checking file elasticluster/conf.py
Hunk #2 FAILED at 105.
Hunk #3 succeeded at 120 (offset -1 lines).
Hunk #4 succeeded at 136 (offset -1 lines).
Hunk #5 FAILED at 667.
Hunk #6 succeeded at 686 (offset 1 line).
2 out of 6 hunks FAILED
checking file elasticluster/providers/openstack.py
Reversed (or previously applied) patch detected!  Assume -R? [n]
```

**Comment by riccardomurri** [comment]
I've rebased the changes in #507 against current "master", can you please try again?

**Comment by verdurin** [comment]
Still seeing patch conflicts:
```
src]$ wget https://patch-diff.githubusercontent.com/raw/gc3-uzh-ch/elasticluster/pull/507.patch
src]$ patch --dry-run -p1 < 507.patch
checking file elasticluster/providers/openstack.py
checking file elasticluster/providers/openstack.py
Hunk #1 FAILED at 846.
Hunk #2 FAILED at 855.
Hunk #3 FAILED at 875.
3 out of 3 hunks FAILED
checking file elasticluster/providers/openstack.py
Hunk #2 FAILED at 867.
1 out of 2 hunks FAILED
checking file elasticluster/conf.py
checking file elasticluster/providers/openstack.py
Hunk #1 succeeded at 1 with fuzz 2.
Hunk #4 FAILED at 575.
Hunk #5 FAILED at 923.
Hunk #6 FAILED at 958.
3 out of 6 hunks FAILED
checking file elasticluster/providers/openstack.py
Hunk #1 FAILED at 958.
1 out of 1 hunk FAILED
checking file elasticluster/cluster.py
checking file elasticluster/providers/openstack.py
Hunk #1 FAILED at 575.
1 out of 1 hunk FAILED
checking file elasticluster/providers/openstack.py
Hunk #1 succeeded at 576 (offset -25 lines).
checking file elasticluster/providers/openstack.py
Hunk #1 FAILED at 972.
1 out of 1 hunk FAILED
checking file elasticluster/providers/openstack.py
Hunk #1 FAILED at 981.
1 out of 1 hunk FAILED
checking file elasticluster/conf.py
Reversed (or previously applied) patch detected!  Assume -R? [n]
```

**Comment by riccardomurri** [comment]
Still, GitHub shows on the PR #507 that there are no conflicts in merge/rebase.  Probably Git does a better job at applying patches that good ol' `patch`?

```
$ git diff master..'issues/#496' > /tmp/507.diff

$ patch -p1 -i /tmp/507.diff --dry-run
checking file elasticluster/cluster.py
checking file elasticluster/conf.py
checking file elasticluster/providers/openstack.py
```

I can email you my locally-generated diff file, but I'm not sure I have your latest email address.

**Comment by verdurin** [comment]
Thanks. Yes, we're getting somewhere now.

However, is there a way of specifying which network to use for the floating IP requests?
At the moment it is picking the wrong one.

**Comment by verdurin** [comment]
Yes, I see you need to set it per node class.

**Comment by verdurin** [comment]
Will test this more today. While IPs were allocated, it still wasn't able to contact the instances.

**Comment by riccardomurri** [comment]
> While IPs were allocated, it still wasn't able to contact the instances.

Do you see the floating IP addresses correctly allocated to instances in the "Horizon" web interface?

Do you see ElastiCluster trying to connect to VMs *also* using the floating IP addresses? (You might need to raise the logging level to DEBUG for this.)

**Comment by verdurin** [comment]
Yes, the IPs are allocated, and when I try a manual SSH to those IPs the connection is made.

**Comment by verdurin** [comment]
These are the errors when it tries to connect:
```
2019-02-18 15:43:38 Evil-Steve.local gc3.elasticluster[32613] DEBUG Ignoring error connecting to master001: Authentication failed. -- <class 'paramiko.ssh_exception.AuthenticationException'>
2019-02-18 15:43:38 Evil-Steve.local gc3.elasticluster[32613] DEBUG Trying to connect to host master001 using IP address 10.1.0.8 ...
2019-02-18 15:43:43 Evil-Steve.local gc3.elasticluster[32613] DEBUG Host master001 (10.1.0.8) not reachable within 5 seconds: timed out -- <class 'socket.timeout'>
2019-02-18 15:43:43 Evil-Steve.local gc3.elasticluster[32613] DEBUG Trying to connect to host worker003 using IP address <IP address> ...
2019-02-18 15:43:43 Evil-Steve.local gc3.elasticluster[32613] DEBUG Ignoring error connecting to worker003: Authentication failed. -- <class 'paramiko.ssh_exception.AuthenticationException'>
2019-02-18 15:43:43 Evil-Steve.local gc3.elasticluster[32613] DEBUG Trying to connect to host worker003 using IP address 10.1.0.32 ...
2019-02-18 15:43:48 Evil-Steve.local gc3.elasticluster[32613] DEBUG Host worker003 (10.1.0.32) not reachable within 5 seconds: timed out -- <class 'socket.timeout'>
2019-02-18 15:43:49 Evil-Steve.local gc3.elasticluster[32613] DEBUG Trying to connect to host worker001 using IP address 10.1.0.15 ...
2019-02-18 15:43:54 Evil-Steve.local gc3.elasticluster[32613] DEBUG Host worker001 (10.1.0.15) not reachable within 5 seconds: timed out -- <class 'socket.timeout'>
2019-02-18 15:43:54 Evil-Steve.local gc3.elasticluster[32613] DEBUG Trying to connect to host worker001 using IP address <IP address> ...
```

**Comment by riccardomurri** [comment]
Are the `10.1.0.*` IP addresses the floating ones?

**Comment by verdurin** [comment]
Okay, that was a mixup over the correct keys to use, because I had to change to a different machine to be able to connect to this network. A new cluster is building now, so I can say that with the patch floating IP support is working. Thanks for your help, as ever.

**Comment by riccardomurri** [comment]
Good to know, and many thanks for testing the floating IPs patch!  I'll try to merge it during the week :-)
