### ISSUE TITLE
Standard oauth2 authorization fails for gce

### ISSUE THREAD

**Issue by zippo7** [gc3-uzh-ch/elasticluster#622]
Authorizing on gce with client_id and client_secret fails as the credentials object in
https://github.com/gc3-uzh-ch/elasticluster/blob/b69208a358315183d3f83e5032b4edb18d6ba5d5/elasticluster/providers/gce.py#L146
will always be None.
The corresponding getter in oauth2client.file.Storage(client.Storage) has not been implemented:
https://github.com/googleapis/oauth2client/blob/50d20532a748f18e53f7d24ccbe6647132c979a9/oauth2client/client.py#L378

**Comment by riccardomurri** [comment]
cc @ndmckinley

**Comment by riccardomurri** [comment]
I'm not sure I understand the context that leads to this error -- if `gce_client_id` and `gce_client_secret` are in the config file, then access works as expected (for me, at least).  

Where are you running the `elasticluster` command? (your computer, VM running on GCE)  How are the credentials obtained?

**Comment by ndmckinley** [comment]
Yes, I have seen this work with `gce_client_id` and `gce_client_secret` set, as well as without (with application default credentials configured through `gcloud`).  What config file do you have that is executing the broken code path?

**Comment by YuzheWu** [comment]
> Yes, I have seen this work with `gce_client_id` and `gce_client_secret` set, as well as without (with application default credentials configured through `gcloud`). What config file do you have that is executing the broken code path?

@ndmckinley Hi Nathan, I also had this failure when trying to start a Grid Engine cluster on gce. Below is a snapshot of the logs and tracebacks:

```console
2019-03-25 00:17:05 Wus-MBP-3 gc3.elasticluster[18311] INFO Starting node `compute003` from image `debian-9-stretch-v20190312` with flavor n1-standard-1 ...
2019-03-25 00:17:05 Wus-MBP-3 gc3.elasticluster[18311] WARNING UserWarning: Cannot access /Users/wuyuzhe/.elasticluster/storage/790161229510-9n2o5gob0p4pr02epce0m9c38bip0kjm.apps.googleusercontent.com.oauth.dat: No such file or directory
2019-03-25 00:17:05 Wus-MBP-3 gc3.elasticluster[18311] INFO Determined that provided credentials are not valid.
2019-03-25 00:17:05 Wus-MBP-3 gc3.elasticluster[18311] INFO Attempting to use Google Application Default Credentials.
2019-03-25 00:17:08 Wus-MBP-3 gc3.elasticluster[18311] ERROR Could not start node `compute001`:  -- <class 'httplib.ResponseNotReady'>
Traceback (most recent call last):
  File "/Users/wuyuzhe/elasticluster/src/elasticluster/cluster.py", line 567, in _start_node
    node.start()
  File "/Users/wuyuzhe/elasticluster/src/elasticluster/cluster.py", line 1296, in start
    **self.extra)
  File "/Users/wuyuzhe/elasticluster/src/elasticluster/providers/gce.py", line 519, in start_instance
    gce = self._connect()
  File "/Users/wuyuzhe/elasticluster/src/elasticluster/providers/gce.py", line 193, in _connect
    credentials = self._get_credentials()
  File "/Users/wuyuzhe/elasticluster/src/elasticluster/providers/gce.py", line 161, in _get_credentials
    return GoogleCredentials.get_application_default()
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 1271, in get_application_default
    return GoogleCredentials._get_implicit_credentials()
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 1256, in _get_implicit_credentials
    credentials = checker()
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 1187, in _implicit_credentials_from_gce
    if not _in_gce_environment():
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 1042, in _in_gce_environment
    if NO_GCE_CHECK != 'True' and _detect_gce_environment():
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 999, in _detect_gce_environment
    http, _GCE_METADATA_URI, headers=_GCE_HEADERS)
  File "/usr/local/lib/python2.7/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 2135, in request
    cachekey,
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1796, in _request
    conn, request_uri, method, body, headers
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1737, in _conn_request
    response = conn.getresponse()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1108, in getresponse
    raise ResponseNotReady()
ResponseNotReady
```

Here is the content of my config file:

```
# Gridengine software to be configured by Ansible
[setup/ansible-gridengine]
provider=ansible
frontend_groups=gridengine_master
compute_groups=gridengine_worker

# Create a cloud provider (call it "google-cloud")
[cloud/google-cloud]
provider=google
gce_project_id=ndsc2019-235417
gce_client_id=790161229510-9n2o5gob0p4pr02epce0m9c38bip0kjm.apps.googleusercontent.com
gce_client_secret=****REPLACE WITH SECRET****

# Create a login (call it "google-login")
[login/google-login]
image_user=wuyuzhe10
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/google_compute_engine
user_key_public=~/.ssh/google_compute_engine.pub

# Bring all of the elements together to define a cluster called "gridengine"
[cluster/gridengine]
cloud=google-cloud
login=google-login
setup=ansible-gridengine
security_group=default
image_id=debian-9-stretch-v20190312
flavor=n1-standard-1
frontend_nodes=1
compute_nodes=3
image_userdata=
ssh_to=frontend
boot_disk_type=pd-ssd
boot_disk_size=100
```

**Comment by riccardomurri** [comment]
@YuzheWu I'm not able to reproduce you error, either:

* If the file `$HOME/.elasticluster/storage/...gce_client_id....oauth.dat` exists, then credentials stored in that file are used, and `gce_client_secret` from the configuration file is actually ignored.

* If that `.oauth.dat` file does not exists, then ElasiCluster tries to "use default credentials" and then goes on to prompt me to paste a verfication code obtained from visiting an authorization page:

```
2019-03-24 20:04:29 monia gc3.elasticluster[24506] INFO Attempting to use Google Application Default Credentials.
2019-03-24 20:04:32 monia gc3.elasticluster[24506] INFO Failed to use Google Application Default Credentials, falling back to config.
2019-03-24 20:04:32 monia gc3.elasticluster[24506] DEBUG (Original traceback follows.)
Traceback (most recent call last):
  File "/home/rmurri/w/elasticluster/elasticluster/providers/gce.py", line 160, in _get_credentials
    return GoogleCredentials.get_application_default()
  File "/home/rmurri/.virtualenvs/elasticluster/local/lib/python2.7/site-packages/oauth2client/client.py", line 1271, in get_application_default
    return GoogleCredentials._get_implicit_credentials()
  File "/home/rmurri/.virtualenvs/elasticluster/local/lib/python2.7/site-packages/oauth2client/client.py", line 1261, in _get_implicit_credentials
    raise ApplicationDefaultCredentialsError(ADC_HELP_MSG)
ApplicationDefaultCredentialsError: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/v2/auth?...

Enter verification code:
```

I see from the logs you pasted that in your case "Attempting to use Google Application Default Credentials" succeeds.  According to https://www.jhanley.com/google-cloud-application-default-credentials/ this means that credentials stored in the file pointed to by environmental variable GOOGLE_APPLICATION_CREDENTIALS are used.  Is that variable set in your environment?  Are the credentials in the file good for the GCP project you're using with ElastiCluster?

**Comment by zippo7** [comment]
I was facing the same error @YuzheWu is taking about. After checking the source code I set the default credentials which fixed the problem.
You are right, the unimplemented method I mentioned is implemented in a child class, so the oauth2client works fine.
Still, if I get it right (see https://github.com/gc3-uzh-ch/elasticluster/blob/b69208a358315183d3f83e5032b4edb18d6ba5d5/elasticluster/providers/gce.py#L138), the `.oauth.dat` file is supposed to be created if it doesn't exist yet, right? Currently, this option will be skipped, even if valid credentials are provided in the config file.

**Comment by riccardomurri** [comment]
Hello @zippo7 ! My understanding of the authentication process is the following:

1. The credentials stored in the `.oauth.dat` file are tried first;
2. If they don't work (e.g., the `.oauth.dat` file does not exist) then "Application Default Credentials" are tried next;
3. If ADC fails too, then you are prompted to visit an authorization URL and enter the verification code you get from there.  After entering the code, two things can happen:

* either the value of `gce_client_secret` in ElastiCluster's config file is correct => good, then "Authentication successful" is printed and valid credentials are saved into the `${GCE_CLIENT_ID}.oauth.dat` file so you won't go through all this procedure next time.

* or the value of `gce_client_secret` is wrong => bad, ElastiCluster hangs forever, never printing the "Authentication successful" line.

So, if it's not working, my guess would be that you *both* lack a valid `.oauth.dat` file *and* have invalid `gce_client_secret` in your ElastiCluster config file.  Does this help?

**Comment by YuzheWu** [comment]
@riccardomurri I did succeed to authenticate after configuring Google Application Default Credentials. Thought supplying `gce_client_id` and `gce_client` through config file is enough. But problems solved anyways! Thanks for your reply.

**Comment by riccardomurri** [comment]
@YuzheWu glad that it's working now!  Although:

> Thought supplying `gce_client_id` and `gce_client_secret` through config file is enough.

It definitely is! I do *not* have ADC configured and ElastiCluster on GCP works fine for me.

**Comment by ndmckinley** [comment]
In the config you supplied, `gce_client_secret=****REPLACE WITH SECRET****`.  I assume you replaced your secret with that to avoid leaking it, but you should double-check the validity of your secret.  I am fairly confident that with a valid secret and a matching client id but no ADCs, the creds work correctly.

**Comment by riccardomurri** [comment]
I guess we can close this now? Anything left unsolved?

**Comment by YuzheWu** [comment]
@ndmckinley I copied `gce_client_id` and `gce_client_secret` (masked here) from GCP console. 

![Screen Shot 2019-03-27 at 8 33 50 PM](https://user-images.githubusercontent.com/19957246/55076418-4b676e00-50d0-11e9-97b4-210b93c5d383.png)

So I suppose this piece should be valid. Or how do I verify?

From the traceback I posted, do you know at which function call is `oauth2client` checking my secret provided in config? I seems to me that my client secret never got through. 

From ElastiCluster source code (elasticluster/providers/gce.py):
```python
    def _get_credentials(self):
        if self._client_id and self._client_secret:
            flow = OAuth2WebServerFlow(self._client_id, self._client_secret,
                                       GCE_SCOPE)

            # The `Storage` object holds the credentials that your
            # application needs to authorize access to the user's
            # data. The name of the credentials file is provided. If the
            # file does not exist, it is created. This object can only
            # hold credentials for a single user. It stores the access
            # priviledges for the application, so a user only has to grant
            # access through the web interface once.
            storage_path = os.path.join(self._storage_path,
                                        self._client_id + '.oauth.dat')
            storage = Storage(storage_path)

            credentials = storage.get()
            if credentials is not None and not credentials.invalid:
                return credentials
            else:
                log.info("Determined that provided credentials are not valid.")
```
My understanding is that when connecting first time, the `.oauth.dat` doesn't exit yet and ElastiCluster
tries to create one. But from the above code I don't see it making use of `self._client_secret`. And no attempt to create a `.oauth.dat` file made. Instead, only a storage object is created with the now invalid path, and its getter is called right away.
