### ISSUE TITLE
Elasticluster fails to start nodes on openstack

### ISSUE THREAD

**Issue by rahuls1071** [gc3-uzh-ch/elasticluster#655]
Hi, 

We are trying to start nodes in openstack with elasticluster.
We are facing below error when trying to run "elasticluster start slurm -n mycluster"

gc3.elasticluster[19601] ERROR Could not start node frontend001: 'int' object has no attribute 'encode' -- <class 'AttributeError'>

Can someone please help provide solution to this

--Rahul

**Comment by riccardomurri** [comment]
There's not enough info to make a guess at what is going wrong.  Can you please do the following?

1. Are you running from the Docker image / `elasticluster.sh` or did you install from Python sources?
2. Can you please post your configuration here (take care to remove password or other sensitive info)
3. Can you please re-run ElastiCluster adding `-vvv` and post the entire screen output here? (Again take care that your OpenStack password might be in there)

        elasticluster -vvv start -n mycluster

**Comment by rahuls1071** [comment]
1. We are running with installation from Python Sources.
2. Below is the config


[cluster/slurm]
cloud=openstack
login=rahuls
setup=slurm
security_group=default
# Ubuntu image
image_id=9f0f13f7-ef5e-461b-b037-b963cca8152c
flavor=m1.small
frontend_nodes=1
compute_nodes=1
ssh_to=frontend

[cloud/openstack]
provider=openstack
auth_url=http://<host>:5000/v3
identity_api_version=3
user_domain_name=<usr_domain>
project_domain_name=<project_domain>
username=rahuls
password=<pswd>
project_name=itcloud
region_name=RegionOne
request_floating_ip=True

[login/rahuls]
image_user=rahuls
image_user_sudo=root
image_sudo=True
user_key_name=US01KVPAIR
user_key_private=/SCRATCH/cloud.key
user_key_public=/SCRATCH/cloud.key.pub

[setup/slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_worker


3. Below is output of command
[elasticluster] testkafka-vm5[rahuls]: elasticluster -vvv start slurm -n my_cluster_rahuls
2019-07-18 21:27:55 testkafka-vm5 gc3.elasticluster[60617] DEBUG Checking section `cloud/openstack` ...
2019-07-18 21:27:55 testkafka-vm5 gc3.elasticluster[60617] DEBUG Checking section `cluster/slurm` ...
2019-07-18 21:27:55 testkafka-vm5 gc3.elasticluster[60617] DEBUG Checking section `login/rahuls` ...
2019-07-18 21:27:55 testkafka-vm5 gc3.elasticluster[60617] DEBUG Checking section `setup/slurm` ...
2019-07-18 21:27:55 testkafka-vm5 gc3.elasticluster[60617] DEBUG Using class <class 'elasticluster.providers.ansible_provider.AnsibleSetupProvider'> from module <module 'elasticluster.providers.ansible_provider' from '/SCRATCH/elasticluster/elasticluster/src/elasticluster/providers/ansible_provider.py'> to instanciate provider 'ansible'
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Using class <class 'elasticluster.providers.openstack.OpenStackCloudProvider'> from module <module 'elasticluster.providers.openstack' from '/SCRATCH/elasticluster/elasticluster/src/elasticluster/providers/openstack.py'> to instanciate provider 'openstack'
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] WARNING DeprecationWarning: Deprecated parameter `request_floating_ip` given to OpenStackProvider; place it in the cluster or node configuration instead.
Starting cluster `my_cluster_rahuls` with:
* 1 compute nodes.
* 1 frontend nodes.
(This may take a while...)
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] INFO Starting cluster nodes (timeout: 600 seconds) ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Note: starting 2 nodes concurrently.
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG _start_node: working on node `compute001`
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] INFO Starting node `compute001` from image `9f0f13f7-ef5e-461b-b037-b963cca8152c` with flavor m1.small ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='http://<host>:5000/v3' OS_USERNAME='rahuls' OS_USER_DOMAIN_NAME='<usr_domain>' OS_PROJECT_NAME='itcloud' OS_PROJECT_DOMAIN_NAME='<project_domain>' OS_REGION_NAME='RegionOne' OS_CACERT=''
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] INFO Using Keystone API v3 session to authenticate to OpenStack
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG _start_node: working on node `frontend001`
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] INFO Starting node `frontend001` from image `9f0f13f7-ef5e-461b-b037-b963cca8152c` with flavor m1.small ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='http://<host>:5000/v3' OS_USERNAME='rahuls' OS_USER_DOMAIN_NAME='<usr_domain>' OS_PROJECT_NAME='itcloud' OS_PROJECT_DOMAIN_NAME='project_domain' OS_REGION_NAME='RegionOne' OS_CACERT=''
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] INFO Using Keystone API v3 session to authenticate to OpenStack
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Creating OpenStack Network API (Neutron) client ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Creating OpenStack Network API (Neutron) client ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Checking keypair `KVPAIR` ...
2019-07-18 21:27:56 testkafka-vm5 gc3.elasticluster[60617] DEBUG Checking keypair `KVPAIR` ...
2019-07-18 21:27:57 testkafka-vm5 gc3.elasticluster[60617] ERROR Could not start node `frontend001`: 'int' object has no attribute 'encode' -- <class 'AttributeError'>
Traceback (most recent call last):
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/cluster.py", line 580, in _start_node
    node.start()
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/cluster.py", line 1319, in start
    **self.extra)
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/providers/openstack.py", line 484, in start_instance
    self._check_keypair(key_name, public_key_path, private_key_path)
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/providers/openstack.py", line 926, in _check_keypair
    fingerprint = ':'.join(i.encode('hex') for i in pkey.get_fingerprint())
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/providers/openstack.py", line 926, in <genexpr>
    fingerprint = ':'.join(i.encode('hex') for i in pkey.get_fingerprint())
AttributeError: 'int' object has no attribute 'encode'
2019-07-18 21:27:57 testkafka-vm5 gc3.elasticluster[60617] ERROR Could not start node `compute001`: 'int' object has no attribute 'encode' -- <class 'AttributeError'>
Traceback (most recent call last):
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/cluster.py", line 580, in _start_node
    node.start()
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/cluster.py", line 1319, in start
    **self.extra)
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/providers/openstack.py", line 484, in start_instance
    self._check_keypair(key_name, public_key_path, private_key_path)
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/providers/openstack.py", line 926, in _check_keypair
    fingerprint = ':'.join(i.encode('hex') for i in pkey.get_fingerprint())
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/providers/openstack.py", line 926, in <genexpr>
    fingerprint = ':'.join(i.encode('hex') for i in pkey.get_fingerprint())
AttributeError: 'int' object has no attribute 'encode'
2019-07-18 21:27:57 testkafka-vm5 gc3.elasticluster[60617] ERROR Could not start cluster `my_cluster_rahuls`: No nodes could be started!
2019-07-18 21:27:57 testkafka-vm5 gc3.elasticluster[60617] ERROR Error: No nodes could be started!
Traceback (most recent call last):
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/__main__.py", line 212, in main
    return self.params.func()
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/subcommands.py", line 91, in __call__
    return self.execute()
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/subcommands.py", line 219, in execute
    cluster.start(min_nodes, self.params.max_concurrent_requests)
  File "/SCRATCH/elasticluster/elasticluster/src/elasticluster/cluster.py", line 487, in start
    raise ClusterSizeError("No nodes could be started!")
elasticluster.exceptions.ClusterSizeError: No nodes could be started!
Aborting because of errors: No nodes could be started!.
2019-07-18 21:27:57 testkafka-vm5 gc3.elasticluster[60617] WARNING ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('<ip>', 58974), raddr=('<ip>', 5000)>
2019-07-18 21:27:57 testkafka-vm5 gc3.elasticluster[60617] WARNING ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('<ip>', 51028), raddr=('<ip>', 8774)>

**Comment by rahuls1071** [comment]
We have used python 2.7 to see if that solves this. Looks like it solves that issues. But it comes up with new error . Below is the output of command

2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Checking section `cluster/slurm` ...
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Checking section `login/rahuls` ...
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Checking section `setup/slurm` ...
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Checking section `cloud/openstack` ...
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] WARNING ImportWarning: Not importing directory '/SCRATCH/elasticluster-2.7/lib/python2.7/site-packages/oslo_i18n/locale': missing __init__.py
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Using class <class 'elasticluster.providers.openstack.OpenStackCloudProvider'> from module <module 'elasticluster.providers.openstack' from '/SCRATCH/elasticluster-2.7/src/elasticluster/providers/openstack.pyc'> to instanciate provider 'openstack'
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] WARNING DeprecationWarning: Deprecated parameter `request_floating_ip` given to OpenStackProvider; place it in the cluster or node configuration instead.
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Using class <class 'elasticluster.providers.ansible_provider.AnsibleSetupProvider'> from module <module 'elasticluster.providers.ansible_provider' from '/SCRATCH/elasticluster-2.7/src/elasticluster/providers/ansible_provider.pyc'> to instanciate provider 'ansible'
Starting cluster `rahuls-elasticluster` with:
* 1 frontend nodes.
* 1 compute nodes.
(This may take a while...)
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] INFO Starting cluster nodes (timeout: 600 seconds) ...
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Note: starting 2 nodes concurrently.
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG _start_node: working on node `frontend001`
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] INFO Starting node `frontend001` from image `9f0f13f7-ef5e-461b-b037-b963cca8152c` with flavor m1.medium ...
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='http://10.193.3.214:5000/v3' OS_USERNAME='' OS_USER_DOMAIN_NAME='synopsys' OS_PROJECT_NAME='itcloud' OS_PROJECT_DOMAIN_NAME='synopsys' OS_REGION_NAME='RegionOne' OS_CACERT=''
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] INFO Using Keystone API v3 session to authenticate to OpenStack
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG _start_node: working on node `compute001`
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] INFO Starting node `compute001` from image `9f0f13f7-ef5e-461b-b037-b963cca8152c` with flavor m1.medium ...
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Initializing OpenStack API clients: OS_AUTH_URL='http://10.193.3.214:5000/v3' OS_USERNAME=''
 OS_USER_DOMAIN_NAME='synopsys' OS_PROJECT_NAME='itcloud' OS_PROJECT_DOMAIN_NAME='synopsys' OS_REGION_NAME='RegionOne' OS_CACERT=''
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] INFO Using Keystone API v3 session to authenticate to OpenStack
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Creating OpenStack Compute API (Nova) v2 client ...
2019-07-19 04:37:04 testkafka-vm5 gc3.elasticluster[47482] DEBUG Creating OpenStack Network API (Neutron) client ...
2019-07-19 04:37:05 testkafka-vm5 gc3.elasticluster[47482] DEBUG Creating OpenStack Network API (Neutron) client ...
2019-07-19 04:37:05 testkafka-vm5 gc3.elasticluster[47482] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2019-07-19 04:37:05 testkafka-vm5 gc3.elasticluster[47482] DEBUG Creating OpenStack Image API (Glance) v2 client ...
2019-07-19 04:37:05 testkafka-vm5 gc3.elasticluster[47482] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2019-07-19 04:37:05 testkafka-vm5 gc3.elasticluster[47482] DEBUG Creating OpenStack Volume API (Cinder) v2 client ...
2019-07-19 04:37:05 testkafka-vm5 gc3.elasticluster[47482] DEBUG Checking keypair `KVPAIR` ...
2019-07-19 04:37:05 testkafka-vm5 gc3.elasticluster[47482] DEBUG Checking keypair `KVPAIR` ...
2019-07-19 04:37:06 testkafka-vm5 gc3.elasticluster[47482] DEBUG Checking existence of security group(s) ['default'] ...
2019-07-19 04:37:06 testkafka-vm5 gc3.elasticluster[47482] DEBUG Checking existence of security group(s) ['default'] ...
2019-07-19 04:37:06 testkafka-vm5 gc3.elasticluster[47482] DEBUG Specifying networks for node rahuls-elasticluster-compute001: fca1782f-10f9-4752-8df0-66541f3c36a4
2019-07-19 04:37:06 testkafka-vm5 gc3.elasticluster[47482] DEBUG Specifying networks for node rahuls-elasticluster-frontend001: fca1782f-10f9-4752-8df0-66541f3c36a4
2019-07-19 04:37:08 testkafka-vm5 gc3.elasticluster[47482] DEBUG Attempting to start VM instance `rahuls-elasticluster-compute001` (dbc0a860-7aee-4a6d-bdad-d513d82c653d) ...
2019-07-19 04:37:08 testkafka-vm5 gc3.elasticluster[47482] DEBUG Attempting to start VM instance `rahuls-elasticluster-frontend001` (1e88553e-092b-42a4-b1a7-08231b9baf7d) ...
2019-07-19 04:37:41 testkafka-vm5 gc3.elasticluster[47482] ERROR Could not start node `compute001`: fault -- <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/SCRATCH/elasticluster-2.7/src/elasticluster/cluster.py", line 580, in _start_node
    node.start()
  File "/SCRATCH/elasticluster-2.7/src/elasticluster/cluster.py", line 1319, in start
    **self.extra)
  File "/SCRATCH/elasticluster-2.7/src/elasticluster/providers/openstack.py", line 606, in start_instance
    vm.fault.get('message', 'unspecified error'))
  File "/SCRATCH/elasticluster-2.7/lib/python2.7/site-packages/novaclient/base.py", line 180, in __getattr__
    raise AttributeError(k)
AttributeError: fault
2019-07-19 04:37:43 testkafka-vm5 gc3.elasticluster[47482] ERROR Could not start node `frontend001`: fault -- <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/SCRATCH/elasticluster-2.7/src/elasticluster/cluster.py", line 580, in _start_node
    node.start()
  File "/SCRATCH/elasticluster-2.7/src/elasticluster/cluster.py", line 1319, in start
    **self.extra)
  File "/SCRATCH/elasticluster-2.7/src/elasticluster/providers/openstack.py", line 606, in start_instance
    vm.fault.get('message', 'unspecified error'))
  File "/SCRATCH/elasticluster-2.7/lib/python2.7/site-packages/novaclient/base.py", line 180, in __getattr__
    raise AttributeError(k)
AttributeError: fault
2019-07-19 04:37:43 testkafka-vm5 gc3.elasticluster[47482] ERROR Could not start cluster `rahuls-elasticluster`: No nodes could be started!
2019-07-19 04:37:43 testkafka-vm5 gc3.elasticluster[47482] ERROR Error: No nodes could be started!
Traceback (most recent call last):
  File "/SCRATCH/elasticluster-2.7/src/elasticluster/__main__.py", line 212, in main
    return self.params.func()
  File "/SCRATCH/elasticluster-2.7/src/elasticluster/subcommands.py", line 91, in __call__
    return self.execute()
  File "/SCRATCH/elasticluster-2.7/src/elasticluster/subcommands.py", line 219, in execute
    cluster.start(min_nodes, self.params.max_concurrent_requests)
  File "/SCRATCH/elasticluster-2.7/src/elasticluster/cluster.py", line 487, in start
    raise ClusterSizeError("No nodes could be started!")
ClusterSizeError: No nodes could be started!
Aborting because of errors: No nodes could be started!.

**Comment by rahuls1071** [comment]
Also can you please help with the version of python that is supported and recommended to use.

**Comment by rahuls1071** [comment]
After using python 2.7 , nodes are being started but elasticluster does not connect to them

2019-07-19 19:00:23 testkafka-vm5 gc3.elasticluster[3045] DEBUG Ignoring error connecting to frontend001: not a valid OPENSSH private key file -- <class 'paramiko.ssh_exception.SSHException'>



--Rahul

**Comment by rahuls1071** [comment]
Can you please help suggest on this issue and how to fix this.

--Rahul

**Comment by riccardomurri** [comment]
There were a couple of bugs in the source, which should (hopefully) be fixed now in the "master" branch.  Can you please update and re-try?  (Both Py2.7 and Py3.5+ are supported, though the former has received more tested.)

**Comment by riccardomurri** [comment]
> After using python 2.7 , nodes are being started but elasticluster does not connect to them
>
> 2019-07-19 19:00:23 testkafka-vm5 gc3.elasticluster[3045] DEBUG Ignoring error connecting to frontend001: not a valid OPENSSH private key file -- <class 'paramiko.ssh_exception.SSHException'>

Plase see https://github.com/gc3-uzh-ch/elasticluster/issues/647 --
this is a bug in the Paramiko library; a workaround is shown in the
linked issue.

**Comment by rahuls1071** [comment]
> There were a couple of bugs in the source, which should (hopefully) be fixed now in the "master" branch. Can you please update and re-try? (Both Py2.7 and Py3.5+ are supported, though the former has received more testing.)

We are already using the latest version from GIT.

**Comment by rahuls1071** [comment]
> > After using python 2.7 , nodes are being started but elasticluster does not connect to them
> > 2019-07-19 19:00:23 testkafka-vm5 gc3.elasticluster[3045] DEBUG Ignoring error connecting to frontend001: not a valid OPENSSH private key file -- <class 'paramiko.ssh_exception.SSHException'>
> 
> Please see #647 -- this is a bug in the Paramiko library; a workaround is shown in the linked issue.

Using ssh keys from ~/.ssh directory and from the machine they were generated worked fine . Only with py2.7

**Comment by riccardomurri** [comment]
So everything is fine now?

**Comment by rahuls1071** [comment]
> So everything is fine now?

This works fine now,  But still py3.5+ fails.

**Comment by riccardomurri** [comment]
> still py3.5+ fails.

Can you please post the error message, a DEBUG-level log, and the full traceback?

**Comment by riccardomurri** [comment]
Since no updates in 3 weeks, I guess the issue has been solved by now.
