### ISSUE TITLE
remove-node fails on OpenStack

### ISSUE THREAD

**Issue by brisk022** [gc3-uzh-ch/elasticluster#657]
I am using a python installation from source (cloned on 2019-06-27; 523c1a53702e2fa5db4b98c10d1d7b89ff67de19) and python v3.6.8. When I try to remove a specific node on OpenStack, I get the following error. 

```
$ elasticluster -vvvv remove-node --yes roman-slurm compute002
...
2019-07-31 10:01:30 roman-elasticluster gc3.elasticluster[10220] INFO Shutting down node `compute002` (VM instance `5077b15d-11d2-452f-b4ae-f65bf9f7f561`) ...
2019-07-31 10:01:30 roman-elasticluster gc3.elasticluster[10220] ERROR Error: unhashable type: 'Server'
Traceback (most recent call last):
  File "/home/ubuntu/src/elasticluster/elasticluster/__main__.py", line 206, in main
    return self.params.func()
  File "/home/ubuntu/src/elasticluster/elasticluster/subcommands.py", line 91, in __call__
    return self.execute()
  File "/home/ubuntu/src/elasticluster/elasticluster/subcommands.py", line 530, in execute
    cluster.remove_node(node, stop=True)
  File "/home/ubuntu/src/elasticluster/elasticluster/cluster.py", line 420, in remove_node
    node.stop()
  File "/home/ubuntu/src/elasticluster/elasticluster/cluster.py", line 1335, in stop
    self._cloud_provider.stop_instance(self)
  File "/home/ubuntu/src/elasticluster/elasticluster/providers/openstack.py", line 682, in stop_instance
    return self._instances.pop(instance, None)
TypeError: unhashable type: 'Server'
Aborting because of errors: unhashable type: 'Server'.
```

**Comment by riccardomurri** [comment]
Thanks for reporting!  Should be fixed in the latest "master", can you please check and confirm?

**Comment by brisk022** [comment]
I have confirmed that it works properly with 28c1a65 . Thanks!
